### ISSUE TITLE
add command support

### ISSUE THREAD

**Issue by kennethgomad02** [DarkWav/SAC#10]
for exmaple command: say this 
in the config

**Comment by DarkWav** [comment]
Can you please provide a better (more detailed) description about your feature request?
I am sorry but i cannot understand what you want right now
A _/vacsay hello_
Command that shows
_[VAC] hello_
In chat?

**Comment by ghost** [comment]
#Action executed after the number of kicks defined. Options: ban, ban-ip, ban-client, custom. Default: ban-ip
#You can use {player} for the player's name.
#If you have Timerban or EssentialsPE,and you want to temp-ban a player,just the action as the following:
#Action: custom
#Commands: (Note: executed as console!!)

# \- broadcast {player} has been banned for hacks.

# \- timerbanip add {player} 120

Action: custom
Commands: say test your hacker!

**Comment by ghost** [comment]
because i planning to excute  my custom punishment

**Comment by daniktheboss** [comment]
Would be cool!

**Comment by DarkWav** [comment]
ehhm i dont know how to execute commands via plugin...
but i´ll se what i can do....
As you MAY know from config, i already have a variable for player names that is %PLAYER%

**Comment by DarkWav** [comment]
added with 3.1.0
