### ISSUE TITLE
Add Aimobot detection

### ISSUE THREAD

**Issue by MisteFr** [DarkWav/SAC#11]
When a player use a cheat it makes a message to the OP but the player isn't kicked.. (i active the option kick in the config)

**Comment by DarkWav** [comment]
### Which check

are you looking for....?

**Comment by DarkWav** [comment]
(for which check did you enable kicking in config.)

**Comment by MisteFr** [comment]
It's enabled, but the player isn't kicked

**Comment by DarkWav** [comment]
which check (NoClip, Reach, ect.)

**Comment by DarkWav** [comment]
(i cannot help you if you cant tell me which check the prolem is for.!)

**Comment by MisteFr** [comment]
All but i fixed it by $this->Player->kick($reason); and i delete the makekick
Can you add aimbot in your AntiCheat ?

**Comment by DarkWav** [comment]
sorry but smoothaim is undetectable, but also won´t give you a big advantage.
this may be added in later versions but is very complicated as it requires a very
complicated Artificial Intelligence.
To your problem: you seem having problems with my new kicking system. it is only a temporary solution so this may be fixed later...
And... sorry for shouting at you :) .... I just was in time stress....

**Comment by DarkWav** [comment]
itll take forever to add aimobot...
