### ISSUE TITLE
Add AntiAimBot

### ISSUE THREAD

**Issue by MisteFr** [DarkWav/SAC#13]
Fly detection doesn't work and speed detection work 1/2. The player aren't kicked too
Can you fix it p's ?

**Comment by DarkWav** [comment]
do you have problems with kicking? i do not support any modyfyed versions of VAC, howver, i´ll se what i can do. Please wait for 3.0.3.

**Comment by DarkWav** [comment]
and to the problem with speed...
VAC blocks speed hacks that give you a singificant advantage.
If a speed hack only runs 50% faster, it might not be detected...
I i do it different, there would be false positives...
I reccomand you for thoose to wait for VAC 3.1 "The Artificial Instelligence Update"
wich willl prevent KillAura and detect thoose "ghost" speed/fly hacks.

**Comment by MisteFr** [comment]
Mmh.. ok when the 3.1 is coming ?

**Comment by DarkWav** [comment]
in a VERY LONG time... sorry. it wil take weeks for the A.I. to be useable.....

**Comment by DarkWav** [comment]
oh it will take ages... sorry...

**Comment by DarkWav** [comment]
EDIT: antiaimbot/antikillaura/antiaimaura is comming this weekend!

**Comment by MisteFr** [comment]
Yay ! And fix speed detection pls cause it's doesn't work

**Comment by DarkWav** [comment]
yes i try to make it a bit stronger.

**Comment by Godsoft029** [comment]
As for CET you have ~4 hours left

**Comment by Aericio** [comment]
Might as well change the repository to Valve Anti-Cheat in 3.1.0 update, eh? Maybe that'll increase the popularity of your plugin :)

**Comment by thebigsmileXD** [comment]
Yes i cannot believe you steal name of valve its copyrighted!!1!

You must change or take down!!1!1!!!

I swear i will report!

**Comment by daniktheboss** [comment]
Lol dan

**Comment by DarkWav** [comment]
@thebigsmileXD: 
This PLugin is named 
# VOID 
anticheat not VALVE anticheat!
the shortcut V.A.C you cant copyight so easily.

**Comment by DarkWav** [comment]
@Aericio i renamed it to voidanticheat.

# THIS HAS INFACT NOTHING TO DO WITH VALVE ANTICHEAT!

**Comment by DarkWav** [comment]
just because of sth is named "vac" it is not instantly "copyright".

**Comment by DarkWav** [comment]
added with 3.1.0.
