### ISSUE TITLE
Op message

### ISSUE THREAD

**Issue by daniktheboss** [DarkWav/SAC#15]
In my server when someone is hacking everyone on the server get the message

**Comment by DarkWav** [comment]
everyone that is OP gets the message. (also players with permission vac.admin.)
make sure none of theese are OP and remeove all VAC permissions from them. this coud be a
upgrade bug.

**Comment by daniktheboss** [comment]
I know they are not op. I use pure perms and took vac perms and it still does it

**Comment by DarkWav** [comment]
since when is that? (suddenly, When you updated VAC, ect.)

**Comment by daniktheboss** [comment]
Idk when it happened.. tried taking the perms away as well

**Comment by DarkWav** [comment]
For now: turn "verbose" off in your config. i have to test some more for this.

**Comment by ghost** [comment]
Try giving them the pernission
-vac.admin

**Comment by daniktheboss** [comment]
Oh hey godsoft. I tried that :/ doesnt work.

**Comment by DarkWav** [comment]
Ehhm i countered some problems with antiforceop
Read the antiforceop file on github not that from vac 3.0.3
Infernus fixed that problem.
QICK: the perm is "legitop" not "vac.admin" for forceop
If you mean the hack reporting: not sure about this.

**Comment by DarkWav** [comment]
issue closed due to inactivity.

**Comment by daniktheboss** [comment]
ok

**Comment by daniktheboss** [comment]
tried at last update as well

**Comment by DarkWav** [comment]
oh

**Comment by DarkWav** [comment]
the theradt isnt inactive

**Comment by daniktheboss** [comment]
i can pull request.. ill take a look into it today

**Comment by DarkWav** [comment]
ok thx

**Comment by DarkWav** [comment]
i think the issue is a real deal, i will now take a look at this bug

**Comment by daniktheboss** [comment]
thanks <3

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
