### ISSUE TITLE
Why AntiAngle and Glide detection is *******

### ISSUE THREAD

**Issue by VeroxCode** [DarkWav/SAC#16]
_[CENSORED]_

**Comment by DarkWav** [comment]
TEMPORARY BANNED.
You were banned from this repository due to rude, impolite and uncivil behavoir and opening useless  issues.
I cannot accept this.
//CLOSED AND LOCKED

**Comment by DarkWav** [comment]
ban expired.

**Comment by DarkWav** [comment]
and please use english

**Comment by DarkWav** [comment]
you can look at this issue: issue #21 
it may help you.
