### ISSUE TITLE
Lag PlayerMoveEvent

### ISSUE THREAD

**Issue by Infernus102** [DarkWav/SAC#17]
![untitled](https://cloud.githubusercontent.com/assets/22660649/20454588/15e5fc74-ae6b-11e6-834d-8edd8bbb756a.png)

**Comment by DarkWav** [comment]
1.58% of your PCT is (in my opinion) not a lag.

**Comment by Infernus102** [comment]
Yes it is, its the laggiest in all my plugins

**Comment by DarkWav** [comment]
if something is the most laggy, it is not atoamatically laggy. It cant be that fast becuase an Anti-Cheat can never be as fast as a for example /fly plugin. ( i have to check all your players 7/24 and this coasts PCT. i cant change this.)

**Comment by Infernus102** [comment]
okay

**Comment by Infernus102** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22660649/20462469/89145752-af44-11e6-93e2-ba46861a2929.png)

**Comment by DarkWav** [comment]
the 1.9 PCT is only 0.4 more, that could have to do with your having more players online.
