### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by daniktheboss** [DarkWav/SAC#2]
Notify admin with perms vac.admin

**Comment by DarkWav** [comment]
ok ill add it when nexp patch comes out (next patch includes AntiInstantKill)

**Comment by Infernus101** [comment]
Also add AntiEnchant, Max Level 5

**Comment by DarkWav** [comment]
@Infernus101 , this is not part of an AntiCheat-Plugin.
use this: https://www.imagicalmine.net/community/plugins/antiabusiveenchants.525/

**Comment by Infernus101** [comment]
i used antiabusiveenchants but they have a problem with dropping item, when u eject an item from hand it goes invisible, it doesnt drop!

**Comment by Infernus101** [comment]
yes antiabusiveenchants has a problem, its confirmed! so please can you add antienchant and make this the best anticheat plugin for mcpe servers ever!

**Comment by Infernus101** [comment]
yes antiabusiveenchants has a problem, its confirmed! so please can you add antienchant and make this the best anticheat plugin for mcpe servers ever!

**Comment by DarkWav** [comment]
yes, maybe, but this will be a past-3.0.1 feature.

**Comment by DarkWav** [comment]
and to the drop problem: GENISYS had problem with dropping! many guys from IM say that its an error of genisys/clearsky and has nothing to do with a plugin. but im not sur about this.

**Comment by Infernus101** [comment]
But when you remove the plugin, theres no dropping problem :(

**Comment by DarkWav** [comment]
Yes because its genisys´ s API that makes the error

**Comment by DarkWav** [comment]
closed with commit 90a5abc1f5412fbcae11fdf1c87882d3a07f1c48
added.

**Comment by Infernus101** [comment]
Added antienchant? Update readme

**Comment by DarkWav** [comment]
NO. only perm vac.admin.

**Comment by Aericio** [comment]
You should really be basing this off of Pocketmine's API, not IM's :/
