### ISSUE TITLE
Toolbox for MCPE-Problem

### ISSUE THREAD

**Issue by Akuroma** [DarkWav/SAC#24]
Does SAC also block the use of MCPE Toolbox? I hate those inventory cheats.

**Comment by DarkWav** [comment]
not directly. it WILL block timer, speed, fly ,ect.
I personally expirienced that item hack cheats are generally not working on genisys.
But ill have a look at it.

**Comment by DarkWav** [comment]
i tested it out... well... dont worry... thoose item hacks are pervented by pocketmine

**Comment by Akuroma** [comment]
No apparently they are not prevented :( I use Genisys for my MCPE-Server. Everytime people come to me and say that someone is hacking items. I've set inventory cheats in the pocketmine.yml to false. But it doesn't help. I've also reported the Toolbox-App in the Play Store..

**Comment by DarkWav** [comment]
and then why is it blocked on my genisys?

**Comment by Akuroma** [comment]
Which option dud you choose in Toolbox? Public Servers or private Servers?

**Comment by Akuroma** [comment]
Ah I think i solved the problem. I forgot to turn off the allow_cheats function in genisys.yml.

**Comment by DarkWav** [comment]
ok.
