### ISSUE TITLE
Speed tracking

### ISSUE THREAD

**Issue by Infernus101** [DarkWav/SAC#25]
Players are been tracked and kicked for speed hacking when they are using Speed 3 effect. This issue has been confirmed and reproduced by me. Please fix this.

**Comment by DarkWav** [comment]
This plugin only supports vanilla effects. if you want to give people speed 3 (which is not vanilla-like, you cant get it by just normally playing MC),
you´ll need to give them the "vac.speed" permission.
However, im looking forwar that the 3.1.1 update will:
- automatically detect if someone has speed and then disable speed check.
- automatically detect if someone has allowFlight and then disable fly check.

**Comment by Infernus102** [comment]
Use $player->hasEffect($effectId); and don't close this issue until it's fixed, that's not right.

**Comment by DarkWav** [comment]
ok im wonking on it.

**Comment by DarkWav** [comment]
ok with 3.1.1 its fixed.
