### ISSUE TITLE
Additional motion from server

### ISSUE THREAD

**Issue by Creeperface01** [DarkWav/SAC#27]
SAC probably doesn't support extra motion from server, (some boosters, leapers), because when player use any of these, he gets kicked due to speed or fly.

**Comment by DarkWav** [comment]
You can make the motions that way that if tey´re active, the player affected by motions gets the "sac.fly" permission, which prevents him from being checked for fly/speed/glide.

**Comment by Creeperface01** [comment]
Then i can remove whole plugin, because if all players can use this motion, and giving permission only for few seconds isnt solution, i made an anticheat that support additional motion quite well, so it is possible.

**Comment by Creeperface01** [comment]
Just use entity motion event

**Comment by DarkWav** [comment]
you can freely modyfy SAC as long as you dont redistribute it. Sorry, but i cant handle that much extra things. You cand also disabled the AntiCheats movement checks OR:

increase the fly thershhold A LOT.  (the threshhold from every movement check.

that makes it still detect fly, bout not a leap.

**Comment by Creeperface01** [comment]
So you wouldnt like to add this feature?

**Comment by TDMidkwhatisxd** [comment]
That would be awesome, if we can block,blocklauncher and toolbox! Almost all cheaters will be gone!
Almost -_- !

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
