### ISSUE TITLE
Win 10 Killaura

### ISSUE THREAD

**Issue by Infernus102** [DarkWav/SAC#28]
Win10 players getting kicked out for kill aura because they can hit fast and from far away.

**Comment by DarkWav** [comment]
i generally are not leaking how the killaura heuristics works, but i can guess what went wrong.
Is this a problem of multiple players or just of one person.
Thanks for bug reporting!
Just a quick info:
the killaura ckeck is obfucated and i do this to confuse
people that try to make bypasses.
For now, set "KillAura-Threshhold to 40 or 50 in config
ill have a look at it myself.
How often does this happen? (didnt happen to me, but i cant ters a lot.)
Have you edited the config of KillAura? (decreased theshhold, ect.)

**Comment by ghost** [comment]
(Not belonging to this issue): The Killaura heuristics arent obfuscated...

**Comment by DarkWav** [comment]
that obfuscation is not oviuly visible. Quick tip: the varibales have completly irrelevant names and are 
actually sth very different.

**Comment by DarkWav** [comment]
im trying to fix that with 3.2.0

**Comment by DarkWav** [comment]
hopefully fixed withhin 3.2.0 if not, please leave a comment.
