### ISSUE TITLE
Can you add Anti InstantBreak?

### ISSUE THREAD

**Issue by xinghao2003** [DarkWav/SAC#29]

**Comment by DarkWav** [comment]
I can try to do this, but i am very busy theese days, so that can take a loooong time

**Comment by xinghao2003** [comment]
thanks

**Comment by TDMidkwhatisxd** [comment]
Hope you add it! There are aura break too!
Can you add anti aura break ? Is like a nuker! I can use this hack and is disturbing!

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
