### ISSUE TITLE
Compatible with Fly

### ISSUE THREAD

**Issue by Matthww** [DarkWav/SAC#3]
I have /fly plugin that makes it possible to fly (obviously)

But is there a way to make this working with your AntiCheat? Because If I have your AntiCheat enabled the fly plugin gets detected and kicks the people...

**Comment by DarkWav** [comment]
ill try to add an "vac.fly" permission in the future. you then have to give it to people that should be allowed to fly. however, it wil NOT be defaultly given to OPs due to ForceOPing.

**Comment by Matthww** [comment]
It's not possible to check if the player has
setAllowFlight(false)
or
setAllowFlight(true)

?

**Comment by DarkWav** [comment]
i can write you an extra plugin that has a functions like this:
setVACfly(true)
and
setVACfly(false)
or i can rewrite your /fly plugin to be compatible with vac if you want.
.
but i can also add more permissions like:
vac.fly
vac.speed
vac.noclip
vac.reach
vac.regen
i think thats the best solution.

**Comment by Infernus101** [comment]
yes do that!

**Comment by Infernus101** [comment]
add permissions

**Comment by Infernus101** [comment]
also does your plugin check regen by potion?

**Comment by Matthww** [comment]
Why not both? I can remake the plugin myself

**Comment by Infernus101** [comment]
thought u didnt know php @flaxues

**Comment by Matthww** [comment]
"Well I'm not that good in php"

**Comment by Matthww** [comment]
Changing some lines is easy

**Comment by DarkWav** [comment]
i will add setVACfly() in an extra API. function and i will add permissions.
but be aware you are not allowed to distribute modyfied versions of VAC. they have to be kept
private.
wait for 3.0.1. i will post the API phar here then.
you can get VAC 301 phat on the downloads. (when its out.)

**Comment by Infernus101** [comment]
okay thank you! Please notify!

**Comment by DarkWav** [comment]
closed with commit 90a5abc1f5412fbcae11fdf1c87882d3a07f1c48
API wil come soon (i am SOOOOO busy)
