### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by asyncthreading** [DarkWav/SAC#31]
Can you make this anticheat to crash automatically people who are using toolbox?

**Comment by DarkWav** [comment]
It is basically impossible to detect what client is someone using, however, i try to 100% block toollbox

**Comment by asyncthreading** [comment]
Its possible to detect lol, some servers are having this feature. Just download a version of toolbox.apk then open it with winrar. To see the source-code

**Comment by asyncthreading** [comment]
The client name knowed as: Toolbox for Minecraft: Pocket Edition  or io.mrarm.mctoolbox

**Comment by VeroxCode** [comment]
This is a bad idea. The most legit players are using toolbox

**Comment by asyncthreading** [comment]
Not even a bad ideea LMAO, if you're legit use a default client.

**Comment by DarkWav** [comment]
VeroX is right, my idol isnt [FPMC](https://www.spigotmc.org/resources/fairplayminecraft-client-side-anticheat.17071/), my idol is GWEN  (Anticheats from MCPC)
ToolBox is not directly a hack. i may consider implementing this, but SAC will for now not include this.

**Comment by majovec** [comment]
Please add antispeedmine

**Comment by DarkWav** [comment]
@majovec issue #29

**Comment by TDMidkwhatisxd** [comment]
Dark! Can you tell me how should i block toolbox? What i should check? :D. !
I really wanna to block that annoying program!

**Comment by ghost** [comment]
Fix AntiKillaura 
It is not working

**Comment by DarkWav** [comment]
@kaliiksPro KillAura is still BETA, so some  false negatives will, of course, ocurr.
I am working on an improvement for antikillaura in 3.2.1.
Thanks for bug reporting.

**Comment by majovec** [comment]
DarkWaw and remove bug ( elytra kicking for hacking fly)

**Comment by DarkWav** [comment]
Elytra bug is hopefully fixed now :)

**Comment by majovec** [comment]
ok thanks you

**Comment by ghost** [comment]
Ok 3.2.1 and killaura still kicking players on windows10... Why you checking time between 2 hits? It is not good idea..

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
