### ISSUE TITLE
Speed detection doesn't work :|

### ISSUE THREAD

**Issue by ghost** [DarkWav/SAC#32]
Can you fix the speed detection?

**Comment by DarkWav** [comment]
which hacked client are you using?
did this occur whilst sombody had the speed effect?

**Comment by ghost** [comment]
The player doesn't have any effect, btw i check your code and the method is good but there is too many conditions before, like checking TPS, Tick, etc.. the code is never used so the AntiCheat doesn't work.. you should just do the distance between getfrom and getTo xz and if it's superior at 5 addSpeedPoints

**Comment by ghost** [comment]
@DarkWav

**Comment by ghost** [comment]
I am using ToolBox and DragOP btw

**Comment by ghost** [comment]
And for your KillAura detection i use and other way to detect it (better, instant detection) check the media https://www.dropbox.com/s/iqf9n61g1b7vvb4/Nouveau%20Film%206.mov?dl=0

**Comment by VeroxCode** [comment]
I have a bypass for the bots

**Comment by DarkWav** [comment]
entities are easily bypassable, thats not a good way. I made much better KillAura heuristics in 3.2.0
I am checking if speed is working correctly right now.
Also: Speed is configured to be Anti-False-Positive-Like. Everything that gives you a +60% speed boost may still work. but ill change that in SAC 3.2.0
Thanks for your ideas!

**Comment by DarkWav** [comment]
hopefully fixed with 3.2.0. if not, please leave a comment.
