### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Pizzahaet** [DarkWav/SAC#33]
Hello,
I was wondering if you could make it so that instead of it broadcasting to entire server make it so it broadcast to people with the admin broadcast perm kind of like a staffchat plugin I can give more details if you need, I'll also send you the staff chat plugin that I have so you can get an understanding

**Comment by DarkWav** [comment]
SAC has many settings. If you want broadcasting off, and staff notify on, make sure 
you have theese settings:

### verbose: true
(staff notify)
<br>
### KickPlayerMessageBool: false
(public broadcast of Kick)
<br>
### BanPlayerMessageBool: false
(public broadcast of Ban)
<br>

That should notify admins, but not broadcast the message over the whole server.
<br>
I hope i could help!
Thanks for writing an Issue!

**Comment by DarkWav** [comment]
If you need any more support feel free to comment!
