### ISSUE TITLE
anti-xray ?

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DarkWav/SAC#35]
Is there a way to block xray? I wonder if is! Becouse is the most silent cheat :0 ! Cant detect!

**Comment by DarkWav** [comment]
There is no way to "detect" it, but there are ways to block it.
This plugin for MCPC can do it already: [Orebfuscator](https://dev.bukkit.org/projects/orebfuscator)
ill consider adding this. may take some time.

**Comment by Creeperface01** [comment]
antixray was already made for nukkit by editing nukkit source, but doing this in plugin would be a lot slower

**Comment by TDMidkwhatisxd** [comment]
No problem! Just add a swich to turn off or on! This way, slow servers can turn it off!

**Comment by Creeperface01** [comment]
But php is slow everywhere 😂

**Comment by TDMidkwhatisxd** [comment]
My server can hold it! I run so many heavy tasks, and my server dont lag so much!
It will hold anti-xray too! 

Dont order server/vps from company that oversell, even dedicated is not good, becouse they use scraps on it! 

The vps im using is faster than my old dedicated server 0-0 !

**Comment by Creeperface01** [comment]
How many players?

**Comment by TDMidkwhatisxd** [comment]
Depends! On weekends 70-80 , and normal 35-50 ! School Started 0-0

**Comment by TDMidkwhatisxd** [comment]
19-50 normal , my bad

**Comment by Creeperface01** [comment]
And server load?

**Comment by TDMidkwhatisxd** [comment]
18-20 , is not stable, but players dont experience lag! (Just internet lag if they have weak conection)!
Load about 20%-50% on 40+ players!
Loads on 70+ players 40%-80% , TPS 14-20 !

Again, players dont experience lag!

**Comment by Creeperface01** [comment]
This is why i run nukkit :D 140 players on bedwars server with anticheat load: 20% :D

**Comment by TDMidkwhatisxd** [comment]
Mine is heavy loaded! All players break stuff, and build! Not to say about other stuff!
A survival server is harder than a minigames one!

**Comment by Creeperface01** [comment]
Yes but still its slow for me

**Comment by TDMidkwhatisxd** [comment]
And i have lots of heavy tasks, that check stuff every 2-7 seconds! Lots!

**Comment by TDMidkwhatisxd** [comment]
Run a survival server for 2 months! To see how heavy load it cause!

**Comment by Creeperface01** [comment]
Im preparing uhc, it should be same, because There are animals etc. There are 3 arenas every for 50 players, so lets see what will happen :D

**Comment by TDMidkwhatisxd** [comment]
I really wanna to use nukkit! But it cant load php plugins, so i wont use it ever!
Ik Nukkit is superior and will be better after is tweaked! But, i dont like it becouse not many plugins!

**Comment by Creeperface01** [comment]
I have only my plugins

**Comment by Creeperface01** [comment]
And you can use some plugins from spugit

**Comment by Creeperface01** [comment]
Spigot

**Comment by TDMidkwhatisxd** [comment]
I dont wanna to learn java to make plugins! And will be lot of work! I will be with php :p

**Comment by TDMidkwhatisxd** [comment]
+ if i go to nukkit i need to reset stuff, so nope!

**Comment by Creeperface01** [comment]
I had a server with php too, then i rewrited everything to Java :D it took quite long but it was worth it

**Comment by Creeperface01** [comment]
What reset?

**Comment by Vaivez66** [comment]
Woah, dude! What's up with those exclamation marks, @TDMidkwhatisxd? Are you that excited?

**Comment by TDMidkwhatisxd** [comment]
A old habit. I see that kids roam too on github.
Do you have something against me if i like exclamation marks? Wtf?! You just spammed

**Comment by Vaivez66** [comment]
It's just irritating, you know? Just like caps, it's not good if you abuse it. And no, I'm not spamming. I'm just telling you now before it's too late for you to change your habit. You will thank me later.

**Comment by daniktheboss** [comment]
Yes, it's very pissing everyone off.... dont! Place! These! Signs!

**Comment by DarkWav** [comment]
i wont be switching to java because i want to support original PMMP and
well....
um...
i hate coding in Java xD

**Comment by DarkWav** [comment]
however, if you want to rewrite the plugin to java for private, non commercial purposes, fell free to do it.

**Comment by Creeperface01** [comment]
I have my own anticheat in java

**Comment by Creeperface01** [comment]
With custom motion support xD
