### ISSUE TITLE
Speed keeps on setting back

### ISSUE THREAD

**Issue by ghost** [DarkWav/SAC#38]
Steps to reproduce:
1: Set speed punishment to 'block'
2: Randomly Jump around and wait for a server lag

 If you get detected, you will be stuck for about 5-7 seconds until the speed detection message stop and you can play normally again.

How to fix: Reset 
x_time_array
And
x_dist_array
on Detect

**Comment by DarkWav** [comment]
Thanks for bug reporting!
Im trying to fix this with 3.2.1, thanks for the idea!

**Comment by DarkWav** [comment]
This person has the same problem #36

**Comment by ghost** [comment]
I think the real issue is the PlayerSpeedCounter. You should reset it to 0 after a detect.

**Comment by DarkWav** [comment]
yeah good idea

**Comment by DarkWav** [comment]
fixed with 3.2.1 thanks for your ideas!
