### ISSUE TITLE
fly issue

### ISSUE THREAD

**Issue by ghost** [DarkWav/SAC#39]
im using this fly plugin -> https://github.com/MCrafterss/MFlyCommand 
and when players who have the fly permission  fly it detects them as hackers and then it kicks them instantly . can you add support for " ->setAllowFlight (true); " ?

**Comment by ghost** [comment]
like can u make it checks if the player has ->setAllowFlight (true); and if its on false it kicks them but if its true it doesn't kick them

**Comment by DarkWav** [comment]
i´ll have a look at this.
Thanks for writing an issue!

**Comment by ghost** [comment]
np , i hope this gets fixed ASAP 

* theres another issue connected to this one which is when players fly and speed while flying it detects them as speed hackers and then it kicks them .

**Comment by DarkWav** [comment]
as i said, ill try to fix this.

**Comment by DarkWav** [comment]
implemented with 3.2.1 :)
