### ISSUE TITLE
Kick issue

### ISSUE THREAD

**Issue by Infernus101** [DarkWav/SAC#4]
Player detected flying, but when got kicked this error on console showed up!
[Server thread/CRITICAL]: "Could not tick level "survival": Call to a member function getAttribute() on null"

**Comment by Infernus101** [comment]
I think it's kick issue because it happened again when a player got kicked for speed hacking!

**Comment by DarkWav** [comment]
I believe this is an error of any other plugin and is not caused by VAC. It has nothing to do with VAC
because VAC dont´t use the function getAttribute(). Check ALL you installed plugins because it is probably caused by them. This will not happen when you set up a server with ONLY VAC installed

**Comment by DarkWav** [comment]
Short: this is an incompatiblity issue with any other plugin. The author of the other plugin has to fix it.
i can sadly not fix it.
but one good thing: the error doesn´t matter. everything should still be fully functional!

**Comment by Infernus101** [comment]
okay thanks!
