### ISSUE TITLE
Security through obscurity is never a good idea

### ISSUE THREAD

**Issue by Thunder33345** [DarkWav/SAC#40]
https://github.com/DarkWav/SAC/blob/03aca35307eecb42f319371e01aa6de7939cc83d/resources/config.yml#L77-L84 
By trying to prevent bypass by not saying the way to bypass it is a bad idea in it's own, basically you already know there flaws but yet not disclose nor fix them but simply not explaining it isnt going to do any help
Your code, it's there:
https://github.com/DarkWav/SAC/blob/master/src/DarkWav/SAC/Observer.php#L730
anyone with enough will could just read through it and understand it then write a bypass
all you are relying as if now is: no one reverse engineered your code, no one is bothered to make a bypass

**Comment by DarkWav** [comment]
1 This is just against noob hackers.
2. The killaura check will be heavily improved within 3.2.1
I once made this, because my old heuristics are not very good compared to the ones from 3.2.1
an i just wanted to prevent noob hackers from bypass.
however, the 3.2.1 heuristics will not be corruped or hidden.

**Comment by DarkWav** [comment]
i know everyone who s good enogh can make a bypass.....
but i can always fix it .......
so, in conclusion, i can tell you´re right.
i already begun de-obfuscating some time ago, but i didnt updated the config yet.
im trying to reval some killaura stuff in 3.2.1.

**Comment by Thunder33345** [comment]
btw shouldnt keeping track if player hit a lot of entities in a matter of few ticks can determine kill aura(the one where everyone gets hit in X range)

**Comment by DarkWav** [comment]
good idea.

**Comment by DarkWav** [comment]
so shall we close this issue or leave it open?

**Comment by Thunder33345** [comment]
close it if you wish so
