### ISSUE TITLE
console Notice

### ISSUE THREAD

**Issue by ghost** [DarkWav/SAC#42]
this message spams the console from time to time (every 30 seconds i guess)

Notice: Undefined variable: effect in /plugins/SAC-master/src/DarkWav/SAC/Observer.php on line 464 12.03 18:27:14 [Server] CRITICAL "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'SAC v3.2.1': Call to a member function getAmplifier() on null on DarkWav\SAC\EventListener 12.03 18:27:14 [Server] CRITICAL Error: "Call to a member function getAmplifier() on null" (EXCEPTION) in "/SAC-master/src/DarkWav/SAC/Observer" at line 464 12.03 18:27:14 [Server] INFO Notice: Undefined variable: effect in /plugins/SAC-master/src/DarkWav/SAC/Observer.php on line 464 

### What version of SAC are you using (do /sac at console to find out)?

I use version:  i just downloaded it 10 mins ago from master branch

### Did you change any settings in the Config?

Config modification (YES/NO): yes
Settings changed:  heres the full config settings 
  - 
  - 
  - 
  - ---
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#ShadowAntiCheat main configuration file.
#Current version: 3.2.0
#What should be blocked?
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#true = ENABLE
#false = DISABLE
#block = block Hack
#kick = Player kick
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
   Plugin-Version: 3.2.1
   Config-Version: 3.5.3
#Enables i am waching you message

   I-AM-WATCHING-YOU: false

#Enable auto banning after an amount of kicks???
#0 = Disabled
#1 = Instant Ban

   Max-Hacking-Times: 0

#Which color should be used in SAC?
#Supported colors:
# 0 = BLACK
# 1 = DARK_BLUE
# 2 = DARK_GREEN
# 3 = DARK_AQUA
# 4 = DARK_RED
# 5 = DARK_PURPLE
# 6 = GOLD
# 7 = GRAY
# 8 = DARK_GRAY
# 9 = BLUE
# a = GREEN
# b = AQUA
# c = RED
# d = LIGHT_PURPLE
# e = YELLOW
# f = WHITE

   Color: 3

#What commands should be executed then?
#Use %PLAYER% for the Players name.

   MaxHackingExceededCommands:

   - "kick %PLAYER%"

#Should SAC show a message when someone gets kicked?
#If yes, which message should be shown?

   KickPlayerMessageBool: true
   KickPlayerMessage: "§7[§eGoldCraft§7]§c > %PLAYER% was kicked for using hacks."

#Should SAC show a message when someone gets banned?
#If yes, which message should be shown?

   BanPlayerMessageBool: true
   BanPlayerMessage: "[SAC] > %PLAYER% was BANNED for hacking. I am always watching you."

#Enable verbose output???
#Sends a mesage to all OPs if someone is hacking.

   Verbose: true

#-------------------Fly-------------------#
#Do you want to enable Fly check?
#This wont have any problems with falling or jumping,
#even if the player has JumpBoost 2.
#This has beem re-written in 3.1.0 and
#takes care of NoDownlGlide.

   Fly: true

#How many moves may a player be flying before detection?
#25 Should work fine. (Standard)
#NEVER set this lower than 10
#Increase if Fly causes false poitives.

   Fly-Threshold: 25

#Wich Punishment should take place if Fly is detected?

   Fly-Punishment: kick

#Wich Message Sould be shown if Fly is detected?

   Fly-Message: "§7[§eGoldCraft§7]§c > Fly is not allowed!"

#Which Log Message Sould be shown if Fly is detected?

   Fly-LogMessage: "[SAC] > %PLAYER% is hacking Fly!"

#----------------KillAura-----------------#
#BETA, REPORT BUGS!
#Do you want to enable KillAura check?
#This also catches AimAura and KillAuraLegit.
#This will block anything that gives the player
#a sanificant gamplay advantage, not useless bots.
#TP-Aura is handled by Speed.

   KillAura: true

#Advanced KillAura Heuristics And Detection (AKAHAD)
#This is an advanced algorithm to catch a lot more
#combat hacks. This is generally aggersive, but
#you can make it even more agersive or rather
#permissive, but i reccomand leaving it as it is.
#How strong should AKAHAD be configured?
#
# 0 = DISABLE AKAHAD
# 1 = PERMISSIVE
# 2 = NORMAL
# 3 = AGGRESIVE
#
# PREMISSIVE will cause close to zero false positives
# even on large servers, but detection is slow and
# bypasses are more likely.
#
# NORMAL will catch most KillAuras, with a very little
# chanche of both false positives and negatives.
# I would recommand this setting because it is the most
# efficent and has the most usability.
#
# AGGRESIVE will catch nearly every KillAura very fast,
# even triggerbots are detected. This configuration is
# very agressive and may cause false positives depending
# on the situation.
#
#I reccomand to use PERMISSIVE if you have a big server.
#For other servers, use NORMAL for a normal server , only
#use AGGRESIVE if you have a smaller server or massive
#problems with KillAura hackers.

   AKAHAD: 1

#How many times must a player hack before detection?
#30 Should work fine. (Standard)
#NEVER set this lower than 25
#Increase if KillAura causes false poitives.

   KillAura-Threshold: 30

#Wich Message Sould be shown if KillAura is detected?

   KillAura-Message: "§7[§eGoldCraft§7]§c > KillAura is not allowed!"

#Which Log Message Sould be shown if KillAura is detected?

   KillAura-LogMessage: "[SAC] > %PLAYER% is hacking KillAura!"

#------------------Regen------------------#
#Do you want to enable Regen check?
#Stops INSANE regeneration.

   Regen: false

#Wich Punishment should take place if Regen is detected?

   Regen-Punishment: kick

#Wich Message Sould be shown if Regen is detected?

   Regen-Message: "[SAC] > Regen is not allowed!"

#Which Log Message Sould be shown if Regen is detected?

   Regen-LogMessage: "[SAC] > %PLAYER% is hacking Regen!"

#-----------------Speed-------------------#
#Do you want to enable Speed check?
#This works with falling.
#This also catches most TP-Aura hacks.

   Speed: true

#Wich Punishment should take place?
#WARNING: setting this to block will
#EXTREMLY lower the combat protection!

   Speed-Punishment: kick

#How many times must a player be hacking before detection?
#5 Should work fine. (Standard)
#NEVER set this to 0

   Speed-Threshold: 8

#Wich Message Sould be shown if Speed is detected?

   Speed-Message: "§7[§eGoldCraft§7]§c > Speed is not allowed!"

#Which Log Message Sould be shown if Speed is detected?

   Speed-LogMessage: "[SAC] > %PLAYER% is hacking Speed!"

#-----------------Reach-------------------#
#Do you want to enable Reach check?

   Reach: true

#How much Range may a player have to be legit?
#This wont affect killaura detection, it just blocks the hits.
#Maxrange will be the maximum range.
#Players are not kicked for that due to
#False Positives.
#Standard: 3.9
#NEVER set this to lower than 1

   MaxRange:  3.9
   
#-----------------Glide-------------------#
#Do you want to enable Glide check?
#NoDownlGlide is handled by Fly.

   Glide: false

#Wich Punishment should take place if Glide is detected?

   Glide-Punishment: kick

#Wich Message Sould be shown if Glide is detected?

   Glide-Message: "[SAC] > Glide is not allowed!"

#Which Log Message Sould be shown if Glide is detected?

   Glide-LogMessage: "[SAC] > %PLAYER% is hacking Glide!"

#----------------ForceOP------------------#
#######################################################
# USE THIS AT YOUR OWN RISK. I GUARANTEE FOR NOTHING! #
#######################################################
#Do you want to enable advanced ForceOP check?
#READ AntiForceOP.txt BEFORE ENABLING!

   ForceOP: false

#Which Permission should ForceOP check?
#THIS NEEDS TO BE AN EXISTING PERMISSION
#WICH IS NOT DEFAULTLY GIVEN TO OPS!

   ForceOP-Permission: "legitop"

#-----------------NoClip------------------#
#Do you want to enable NoClip Detection?
#This prevents players form glitching through blocks.
#If this caueses bugs, please report it to the Author!
#Lag with stairs has been highly decreased with the update
#3.0.2. IT STILL MAY CAUSE GLICHES!

   NoClip: false

#Which Punishment should take place?
#I do NOT reccomand to kick players for NoClip due to glitches!

   NoClip-Punishment: block

#How many times must a player be hacking before kick?
#i reccomand setting this to above 50 because of pocketmines
#bugs and glitches.
#NEVER set this to 0

   NoClip-Threshold: 75

#Which Message Should be shown if NoClip is detected?

   NoClip-Message: "[SAC] > NoClip is not allowed!"

#Which Log Message Sould be shown if NoClip is detected?

   NoClip-LogMessage: "[SAC] > %PLAYER% is hacking NoClip!"

#--------------ForceGameMode--------------#
#######################################################
# USE THIS AT YOUR OWN RISK. I GUARANTEE FOR NOTHING! #
#######################################################
#Do you want to enable ForceGameMode Detection?
#USE THIS WITH CAUTION!
#This WILL BLOCK ANY PLAYER THAT IS CHANGEING ITS GAMEMODE
#AND IS NOT OP ALSO IF DONE VIA ADMIN/PLUGIN!
#I WONT GUARANTEE FOR ANY FALSE POSITIVES WITH THAT!
#READ AntiForceGM.txt BEFORE ENABLING!

   FoceGameMode: false

#Which Message Should be shown if ForceGameMode is detected?

   ForceGameMode-Message: "[SAC] > ForceGameMode is not allowed!"

#Which Log Message Sould be shown if ForceGameMode is detected?

   ForceGameMode-LogMessage: "[SAC] > %PLAYER% is hacking ForceGameMode!"

#//////////////////////////////////////////////////////
#//                                                  //
#//     SAC by DarkWav.                              //
#//     Distributed under the AntiCheat License.     //
#//     Do not redistribute in modified form!        //
#//     All rights reserved.                         //
#//                                                  //
#//////////////////////////////////////////////////////
...
  - 
  - 
<br><b>[...]</b>

### How to reproduce the issue?

Reproduction:  idk

-----------------------------------------------------------------------------------------------------

**Comment by Matthww** [comment]
Reproduced. While sprinting from and on slabs

**Comment by DarkWav** [comment]
Thanks for bug reporting! This is a critical software bug so i will fix it ASAP :)

**Comment by DarkWav** [comment]
fixed with 3.2.2 :)
