### ISSUE TITLE
Speed detection is broken

### ISSUE THREAD

**Issue by VeroxCode** [DarkWav/SAC#43]
Speed detection doesn't work with a 100% Speed!

I use version: 3.2.1

Config modification (YES/NO): YES
Settings changed: 
  -  setted all punishments to block
  - 
  - 
  - 
  - 
  - 
<br><b>[...]</b>

Reproduction: use Speedhack with motionvalue 1.2 

------------------------------------------------------------------------------------------------------

**Comment by DarkWav** [comment]
thanks for bug reporting! This seems to be a bug in the block punishment. Does this also happen when the punishment of speed is kick?

**Comment by VeroxCode** [comment]
It happens with kick of course, I think theres something broken in the detection

**Comment by DarkWav** [comment]
fixed with 3.2.2 :)
