### ISSUE TITLE
Elytra

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DarkWav/SAC#46]
Please add a option to increase the speed time wen player equip a elytra. Players gets detected for speed ;-; , wen using elytra.

**Comment by DarkWav** [comment]
Which elytra plugin are you using? you need to do $player->setAllowFlight(true);
in your plugin.
Sorry for my inactivity, but i had exams coming up.

**Comment by DerddyDert** [comment]
Players are also getting detected when using Speed III effect...

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
