### ISSUE TITLE
Kicked for fly when climing ladders

### ISSUE THREAD

**Issue by Guillaume351** [DarkWav/SAC#47]
### What version of SAC are you using (do /sac at console to find out)?

I use version: 
3.2.3
### Did you change any settings in the Config?

Config modification (YES/NO):  NO
Settings changed: 
  - 
  - 
  - 
  - 
  - 
  - 
<br><b>[...]</b>

### How to reproduce the issue?

Reproduction: 
Climb ladder with default settings.
------------------------------------------------------------------------------------------------------

**Comment by DarkWav** [comment]
Thanks for bug reporting! This has to be a bug in antifly, i will fix it ASAP.

**Comment by DarkWav** [comment]
i have fixed this in [3.2.4](https://darkwav.github.io/ac/SAC_v3.2.4.phar), but expect another hotfix today! (a killaura thing.) (3.2.4 isnt official, 3.2.5 will be offical.)

**Comment by DarkWav** [comment]
fixed with 3.2.4
