### ISSUE TITLE
Arrows deal 0 damage

### ISSUE THREAD

**Issue by Guillaume351** [DarkWav/SAC#48]
I use version: 
3.2.4 
### Did you change any settings in the Config?
NO

Reproduction: 
Shoot an arrow on someone else. Receive no damage (at least on SteadFast)
------------------------------------------------------------------------------------------------------

**Comment by DarkWav** [comment]
ill try to reproduce at PMMP and then i will try to fix it.

**Comment by DarkWav** [comment]
it is a critical killaura false alert, i will fix it asap.

**Comment by DarkWav** [comment]
fixed with 3.2.5
