### ISSUE TITLE
Suggestion to fix one of the false-positive

### ISSUE THREAD

**Issue by Guillaume351** [DarkWav/SAC#49]
If you spam to do a tower block under you and build is disabled, you can get kicked for fly because of the delay for the blocks to disappear. Maybe when you place a block it should reset your fly hack count ? (if the coordinates of the block is just under you ?)

**Comment by DarkWav** [comment]
i will try to fix it with 3.2.5.

**Comment by DarkWav** [comment]
fixed with 3.2.5
