### ISSUE TITLE
I am watching you message

### ISSUE THREAD

**Issue by DerddyDert** [DarkWav/SAC#50]
I just downloaded the new update. I noticed that even though I set
`#Enables i am waching you message
   I-AM-WATCHING-YOU: false`
It still shows the I am watching you message on player login. How can I disable this message?

### What version of SAC are you using (do /sac at console to find out)?

I use version: 3.2.5

### Did you change any settings in the Config?

Config modification (YES/NO): yes
Settings changed: 
  - 
  -  #Enables i am waching you message
  -   I-AM-WATCHING-YOU: false
  - 
  - 
  - 
  - 
<br><b>[...]</b>

### How to reproduce the issue?

Reproduction: 

------------------------------------------------------------------------------------------------------

**Comment by DarkWav** [comment]
i will have a look at this later today.

**Comment by DarkWav** [comment]
sorry, i tested this on the latest PocketMine-MP version and the bug did not occur.
What you can do:
* Reset your config entirely (delete you config.yml file and then reboot the server) and try to diable it again.
* ALWAYS reboot your server after config changes.
* make sure to use WordPad if you edit the config.
* make sure to not convert the config file.

**Comment by DerddyDert** [comment]
I did all that once using notepad and again using programmers notepad. The version I used was the latest at: https://github.com/DarkWav/SAC/wiki/Downloads
SAC [1.X.X]
3.2.5

**Comment by DerddyDert** [comment]
I followed your recommended procedure. Also I did a more thorough way but having SAC generated the default config and then shut the server down then edited the file using WordPad and saved the file. Nothing seems to work. Note: all other changes in the config are being implemented. Could you hook me up and let me know which lines I could simply comment out in the code? I see the i am watching you and i am still watching you referenced a lot in the code... Thanks

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
