### ISSUE TITLE
Report Feature?

### ISSUE THREAD

**Issue by BlockCraftMCPE** [DarkWav/SAC#51]
Hello,
I love this hack blocker,but i also have some ideas(listed below)
- A Report System included in SAC
- Report logout and Login
- Lower laggs(My Server laggs when i use the plugin)
Thanks for reading,
BLOCKSTORM

**Comment by DarkWav** [comment]
Thanks for you ideas!

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
