### ISSUE TITLE
Cobweb => Fly detected

### ISSUE THREAD

**Issue by Guillaume351** [DarkWav/SAC#52]
No settings changed in config.

**To reproduce :**

Fall/Go in a cobweb and wait just a few seconds

**Comment by DarkWav** [comment]
first of all, sorry for the insane delay of my response. I had a huge amount of holydays (14 days).
and 2 weeks of exams before. I will reproduce this ASAP, seems critical.

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
