### ISSUE TITLE
There is a Error with the Hacking Message!

### ISSUE THREAD

**Issue by ghost** [DarkWav/SAC#54]
Hello!
When someone is Hacking it comes like this Message: <Player> is Hacking! NoClip! But EVERBODY see it, Not only the Operators..

**Comment by DarkWav** [comment]
first of all, sorry for the insane delay of my response. I had a huge amount of holydays (14 days). I have already been told about this error and it only happens on some servers. i am trying to fix it but i will have to take a deeper look in the code and it may take a while. For now: Set the value "Verbose" to "False". This should disable these messages for everyone. I hope thats a temporary solution. I am currently having more critical bugs to fix (The cobweb-FP-glitch, ect.)

**Comment by DarkWav** [comment]
The bug has already been discovered in #15

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
