### ISSUE TITLE
OP error and glich

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DarkWav/SAC#55]
I have permission legitop but I still get detected. Why?

**Comment by DarkWav** [comment]
first of all, sorry for the insane delay of my response. I had a huge amount of holydays (14 days).
I will take a look at this soon. Probabyly something bugged in the configuration.

**Comment by dries-c** [comment]
do not have this problem

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
