### ISSUE TITLE
NoClip cheat detected when player in y 30 or y 31

### ISSUE THREAD

**Issue by xinghao2003** [DarkWav/SAC#56]
### What version of SAC are you using (do /sac at console to find out)?

I use version: 3.2.5

### Did you change any settings in the Config?

Config modification (YES/NO): NO
Settings changed: 
  - 
  - 
  - 
  - 
  - 
  - 
<br><b>[...]</b>

### How to reproduce the issue?

Reproduction: 
Just go to Y 31
------------------------------------------------------------------------------------------------------

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
