### ISSUE TITLE
fly glich

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DarkWav/SAC#59]
SAC kick players if they run on fences or stairs.
TESTED JUST ON FENCES

**Comment by dries-c** [comment]
i know

**Comment by dries-c** [comment]
trying to fix it

**Comment by dries-c** [comment]
speed or fly??

**Comment by dries-c** [comment]
also on slabs??

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
