### ISSUE TITLE
Some bugs and comptability with the /fly

### ISSUE THREAD

**Issue by MisteFr** [DarkWav/SAC#6]
The Reach and the glide detection doesn't work properly, they kick some people who don't cheat.
And can you add the /fly comptability ?

**Comment by DarkWav** [comment]
I will increase MaxRange with the next update.
Im working at /fly.
Glide - what did theese guys do? Stuck in cobweb - or something?
For now:
Disable glide
Set reach plunishment to block
Disable fly and speed if the /fly command is important
I will fix this ASAP
thanks for bug reporting

**Comment by MisteFr** [comment]
Ok thanks, and yes /fly is important, for the glide it's because people spawn in cobble

**Comment by DarkWav** [comment]
closed with commit 90a5abc1f5412fbcae11fdf1c87882d3a07f1c48

**Comment by DarkWav** [comment]
you ll need to modyfy you / fly plugin so it gives the permission "vac.fly" to the flayer whilst flying.
