### ISSUE TITLE
Additional Thing

### ISSUE THREAD

**Issue by BlockCraftMCPE** [DarkWav/SAC#61]
I have made another feature request long time before,just wanna say that the idea mean for an Login / Logout like /sac login to get AntiCheat Messages and Reports from other Players and /sac logout to disable it.And Please add Language File Support :)
Wanted Commands:
/report <login|logout|teleport [tp]|<Player>>
/sac login
/sac logout
/sac vanish

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
