### ISSUE TITLE
PocketMine-MP_1.6.2dev-305 Crash Dump with SAC_v3.2.5.phar

### ISSUE THREAD

**Issue by teracube** [DarkWav/SAC#62]
Hi,

Unable to restart my server with this configuration :

PocketMine-MP_1.6.2dev-305_1a7f567a_API-3.0.0-ALPHA7.phar
SAC_v3.2.5.phar

Crashdump message  :

PocketMine-MP Crash Dump Thu Jul 20 22:04:17 CEST 2017

Error: Declaration of DarkWav\SAC\SAC::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool
File: SAC_v3.2.5.phar/src/DarkWav/SAC/SAC
Line: 148
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[139]         $player = $observer->Player;
[140]         if ($player != null and $player->hasPermission("sac.admin"))
[141]         {
[142]           $player->sendMessage(TextFormat::ESCAPE."$cl" . $message);
[143]         }
[144]       }
[145]     }  
[146]   }  
[147]   
[148] }
[149] 
[150] //////////////////////////////////////////////////////
[151] //                                                  //
[152] //     SAC by DarkWav.                              //
[153] //     Distributed under the AntiCheat License.     //
[154] //     Do not redistribute in modyfied form!        //
[155] //     All rights reserved.                         //
[156] //                                                  //
[157] //////////////////////////////////////////////////////
[158] 

Backtrace:

PocketMine-MP version: 1.6.2dev #305 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: 1a7f567a70c58b0848def59118aad16557750ff3
uname -a: Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64
PHP Version: 7.0.17
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
DevTools 1.12.1 by PocketMine Team for API(s) 3.0.0-ALPHA7
ItemCasePE 1.1.0-dev1 by aliuly for API(s) 3.0.0-ALPHA7

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvtv40aS/lc6soEdH0RalCzLZuAAhu3czmGc8Y09mB+iYNAimxLXfIXdtKwE87/fV9XNhzy+
2UeywA6QmOxHdb3rq6Z+H5k0V6MwmE8m87NgMl+MR6quy3oU/j4yuwpTo5vPV+9v796+u/l88+HD
+w+j8ShXWss1zV2rKJO1NGlZiDIR17J+/CSflsv7yyv+XxiWxVWZ57KI31Rl9KhMnhZquYzs2HLp
Ju9VEataHGr+OxbfWisOozwei8NMrlQ2FrKu5U4cynqtj0TeaCNWSmBPBa5WmRLb1Gy+Se/mWUWN
Ket/E6/2YSy0qdNi/SrboViVZQbFJmlGWoXiPj/N/Kk/96uNrI91HR071R5jjv7D4gwnwnInZ1/G
oypr1mkxCk3dqPEoKmNFBgxm56Am3L/DKpM7MH4hDsuVVvWTqr0f7njse5ALTiaDxWki3rQbvrsQ
RZNlguWxY94PG6nvVJ2nWsP2b5YjLSNfxtDCcnR0xOSCAbnfeWQ6GBE9KVLkrXWpNw/q2fxY1rk0
YXhzf3V5d+MvR4dRthwJXxw6xzuy/M4G5L7wyEk3Yt/n7v2LEPx+yu/t24Lf+PEMj3YLaYwe5qSN
43/pH28PeLv4p/+57dN+O6wtVrs2tvx/aPus336dkuetGqNi0bDnmo0Sl4VJrzZKGvEujVShlT/c
fjLYXoqiNKJWcUdHpIXIy3iXpCCZwFjfvTh93m+/hN/U6XpjNEiw08X+32P+9I+pbvHHDAdXIG9H
UJlaRoijn38Zj9aqULXMKKgKSQlzdMdRf4sY9G7vsBHRRJGAmcA/9aexesLgqkmzeBTOJnOEaF2a
MkKYh0EwG49klWLtzJ/4E+/y3d1fLxdYv04NEZCLZH66kItJND9bTc5OzmKVzM+D4EzKODidzxeL
+SRJZthQy8csXWHPxD/zJxhoHHvv0qJ5FoWeTaaz6SLw08qDT3pnE286m/iqESf+iR+ce7Cjp03s
pdXTqXd6Ig4CcX97J26Rzy+btZhORTALJ/NwEoirm/sHMZ0Ep+L57PTz6QlOqzYVzlpAiIDY/w2B
3AplZz+XumUGA/yS8UuXszTp9Fo9PSAD6oF+u6F91QZTP8CQbMymrLH+54EhxIOS+egXp9uf95WL
YVVIFARwmMhMI03GqgLD2lpYl4m5Hg7kkhJqx8dyOeAoKyUJev9w+eHhI1l/q1Y6NcT3xphKh8fH
MOWmWflI/8c9h8cdDcj/1qj8Smp1dzMQezD4QnCIAqd6IbzM0ibb/dkyW6rLJSTKIzBTobLd0lQn
+d37+4dP7z+8u96TffSFzAo8kCuj6vYQrjQ+3L9StUkV+cDBXfcmrsoiSdeCSt+yXhYHD5tG/E+T
wdPgfeHkJAwWnestaEVemvhi2UwmcnFu/zx+9519SNqHqH2ohf2r7J/sAWF81QAhhNfiH6ZBp7qC
WZW1uQjOUWqYFZWX9c7L0jw1F9PJ9OSWRrcbqAOD2lyUSUIjsijKpoiU50qejDapelK5Koy+KAum
X8lt4VGSUBHBqYv5hE+Qz26TdiMyy8qtl2SUVFv6drMs0hxW3iOYo9S7gbUkdmN1wWSQt8FPN+YI
AW3EUVl379VT5XbHaZKkUZOZ3cWUqXFGBGzytDIGyEZf0HAGsTKPnPliW9ZZ3I9ppeLBEgKXF9c3
P15+fPdAo9ZRvV8bVe/ckW6ojqANO0KPfiW1Bu344r/4HzQC9OZp+aRaya2p0upiPfM3Ob0i49FM
WRBo8oYSP6Vq61Ftk7DPxRkNUerqMJ2/yzPyWEEBAFxJzto4xEs+SwVQ7BUD+LB42KDYiVYzAHuK
q25ZwOHNBlU3IpdgqJoWUdbEqKQg/1WsEK37MlcErs3XNLVM1FiUmKk1kRSrWslHsSub2tEiIAdx
U67VOKqsa/gXghuEf1LbjtwxSoyEdbXYlsVfjJBVpWQtSLXAYmkEr9uBfTCRaiv3dqMK0VTrWsYg
4C8LUrwlFi4LgTiuFaIAQ+Aik8W6AXITBE1ZZc5IOsV7VoJ++hsrlbYCmEROiv2NYKDNr6rwt+lj
WgGXSL+s18f0dvwOhvxcJp/f3r//fDo796afaR/U2BEKxRJJcb0c0UGfNop0J0wpCIQKSOlwOsxU
y0JnkmATT7M2mVPwgSdl2KTIyQBQYgNwnLGRcxC2wdUfyckX43rTmLiksLRAlpi5t5SjrNQqtmxd
UogLSiDUMbg6KZ5SKf6XwgNLOEw8NxMKgv208X6DfZK8VJfgxp1iTSUdIdFoOCHqAByBpbu8e4uV
KCkx6amf8MDWCkz15G84IFs61A5QrhBwV3gEsQqY6vwIy134drO9Gg4+pVA0gnEnZBwTMLSeR2zC
1x7BjtRNzflRwN/QMEEuKF392siMzLFOn7D2SWaNEm/ckSgQRyBuz0PaUJSrPVhzvVZ1iFk6+acm
X0HbCKdLvSuiB6kf4fH1IwLIp/mP2mLaTkhatalL5G+4BFbrseDEJlwChMuOud2EFFSsWS0oiTSW
NwUih5Yw7Xt2GciD4KrLZyRro6ACiMOuXnSskVYtO28TilBaQpE4Fqn5CzRnat4VK6oV7IUv9oo3
kAB2FlPSCMvgOSlDpkTRaosXx+p/Z+UKiiU8IOyw4JrGSF+t5WpnwJC4t6xM+PBUk3ltpEOmbcqM
sbIFVShXG92QZr0kKdwFaQoVoGBSCXJEe6I1P4Rp2GnXJeQon7hfSckz18ykLbahmCw5VXBWNkg1
Mv4PZ5+w1TeYp8r7h5jXpqz4fJeqOn4cNS0QUlQ7kWUcN3Rmy1IA9GK5QlufllyOKBY1HRhxQnbc
dfEW4Cikmph8jFd4iAdlI43TeIkms0CEQm+UHf4/tVp1AjVlnOEp1u2yJRdcooHo6yPZpiM64T2l
EKpwvNz/ejGJ7SAwVFipiAqhZrUQr1bHdm8nADSpKt2LOZs4OfXRqww5qWdW6rWsV7C/h04vs0iO
IuxVrbI7EStuj3B7ELu5LBouuUMuAEfQfeujcZsTXjiD8wabV5OkzQ1572W+eG/rHb/BIzZlk8Ud
IykyyLYQPevkt6JiziHg6WRiZRQHP3IkfJUb2Vfs7k6opC7zNsXSXjfvDbPSwKYQwpnupSu84j+D
fQSUo01TPGqr71uJBNvkKC5859EiPJJGuHstjpD+CPIVR5dDRDA5j/BNg7R54ti7Lu3ES6vxFWjR
UqClrX9YOm7ZnyAq1x8vQhOhrLDOBdqDaKIr2t8ktSwKZcgEHWKDR2S2AK6kQZdC+EMSuEXdgxu5
ZMRxZ/Gom7U5yN28UilkFR4Ms1Y7Q/Fe7wzRHgsvGPgwlTw+1jMtK8gm81ObTPoSyx0E1bfY2pCw
G8MP2otBx5Mv/oomiW88c8IpV3cfx9gLDlZIO9s0NhubrDmsO/Iekw/FwuGBHiloVsxgqS8uY4TR
RmbJMbC9BS+xgnu5g3CkoJaZLDyIw64oD2gN4NHNM8UcoR+ZjW0808Gf0gLgEWLBbRTHGpX4j3fF
XQsQeqhO2Ic2bZHil4TTi8pzr0Mohr5OrZq1NX/pUqWgIlGzQyu+G2eMQzmHLnj8blaTRzB0qTaV
nxYpsRGwbO0KG4ufZF1Qmh7spO7FJWai4giMRYxyQcL0K3OJyMxhUkNKrJuCvlhQGNPNI4c0KLc5
no6DjIWXJp4b6yOhxa+wQbklf1HPkarsKRYi96cmMoXq2am54RblysB+tIt9CdgLK5h55qMLfyTc
xM501MZi1RiWI5JkMdmW6KiWesM8D4CevajBIpKDzmsjq5ap5gNRn8ijkl4QwiStLEyPZ7xubOBb
OOgHERCSdLCBWgZ2grZdYLOSHK6NWLqAC9m2TolaHCOhmgZp4Xgd2QCi7xy6P2pZ2Dwb2pauRCtB
am4bLtU2E5yLY2mgFvlkW0l66i5LaKozooT5keeUNGGrN6cwh+AYGSOmGFPoSpEhgDGKMsrSSvBO
RNBtZ4y8fGr7DN0obT8XaWq5V2j2Hskz0mjD/koN+w5Gsu15xm6Z8WbnefZqpqVo2RwoZMgtObG2
R9imXVudUNvjdKK7Q5kQaWbA95/GLvmTZBYGWaG9stnr51Xb3Anr8vYmg5e6/N9o12xGoGe4BLgt
nt0Sigpe8pRm3ObuZawILTSqqSPHmZTRGNRCmZOij+4ELXqiKm5BGfkE3f/QuENiravsDbc417aB
91SyyMdXUqvBYW8CFItXThmLKSaC1yaUifwjLlxaDbngYHkgynSr0JpUoTjb88hDrbL4/qa/2KFi
yCmHGgcylMy2cqctbUdnYCpb9F0JbBO5U6bLMwXpPnsJhcbtqr0rsFevobgXvcxLJF/uMRlnUdnl
jNXKRlohJqkJR9zSI8MmcfCBMdRgK3tOoezdykpZUiuVUGrli0vKamQfS5syAl9nDsAYjIgkYZNp
StdHiq4jqp27KnMgrQP4XEETqQ2rmpXl6nvSZPaLljbZzqOslkYWY3FZqOl+yjDzraB/K+lmwKJr
LXPF0Uw5kJBXi0L7lPsKhmh5JjGdSuxw4S7TWnxgIaj6FbFuvjI6abg1OvCukC8tBAtGjMV6v9s3
zuRV68gadGK+MeLkDBu5rc6/rRFmVBnoGtprKiRpNZA5ypS0h/A9eH+F9PaaD3LJilIUOZAt5ghB
AJxcOLGErWUtuOUtQ5HFgYeoPBBrVFHdK6W/l2n14n+tGFfhtjLlKzao1+IOuKLbz8mLxz0N3wrF
2b9ErSqrJnPU3DNBzBeElwXnFa+y1dJe5Hvs8uTs1HbBP6nw191o4FIclcpQ2N6s9UBov2iqUJzb
hs3GDidAi8gcLVCZ8zZ3Yv++lXRUNxrYRfkqRZy2rS7nV3vLFtqcSheCBGmEHbU+7XzQxttLTEYO
79EV7f5IV3j2RgESCW31XrYpybUsihrc2KOnYf6Kstjl1KhzTGuoWHeM0s2Dmxb9NDPMUESu17Va
u+u97uKU2j36Kvz4ujSWHyKnX+OH9GUjha38cjfcws6GHYp1CKyHsDxaVoMr3yu69edraJWVFVV3
wE2AU7oupcJuuyoAokTV6Gs9yvkFgTla5ABhoxlEDokI9+1xABQb9I7a2KLRpmdHjSxkp1v6+oVS
ttvtKypB3uzwhUOIRJW2tO0NWYQKFJ3IvYbb094a+90RbsKv8hzNBF9xtvr7JgJ1RZLN5jzXZp8h
CAZ1Y1V58NP7h5uQvvDYMU5XdJvgYLrLV3StvUa3xW1gmnR0ojKDFD22G3QuTM5l5rZDR5EArrAa
unmWhODsC+F28OfMFLb24ilkBLoNDMXPjKOBJsZ8PfgLUbSVrYV0wy9KLAFdWdb0UYYvptqPfNyc
vIYMGFwzXNHc6HKDBLukYNRhuQHrfCozwE+CvglSfuNy3p8Wih/fXT6E0+8X4/n5czCePc/G0++D
72NALpva35ha4QVp+OJsYiuAfTuZH/EHPPVsAKaplaOP61fAFcMfKlCUDd+raH9e/5qlRs34dxUL
z/6W4zf7Q4tuzSoCdt0MR+jTUBHLem/M/YiuH2jqbPiepBnywd6I2ftRxTree8v3JjdIffzzAPq9
xd+0+63ACb/mK/spa7g+j+pdZYYj93fv9jVRmD3+CBVCpj0mqlKnz3sD7kKRf/wR+KcY+qASdyu2
R22Tl3sCaM4Jeo/HHdTPPyRxT2JOU1Oyg/DoZwDzyclkgcfDt/Ce1Tyan09O45P5VNHTYjaV57PV
ZB4ks7PpQk2mi5Pz1dlMHIL23YbNMwXBKV5N+agKFOE9/X9CK4R0ycaf+fQrm53kb8BT97uW39LK
/iRj5s9bftOewpcv/weTn/1N
===END CRASH DUMP===

Thanks for your help

**Comment by dries-c** [comment]
$label is a string

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
