### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by AyyItzJ4y** [DarkWav/SAC#64]
PocketMine-MP Crash Dump Sun Oct 1 03:25:37 UTC 2017

Error: Declaration of DarkWav\SAC\SAC::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\plugin\PluginBase::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool
File: SAC-master/src/DarkWav/SAC/SAC
Line: 148
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[139]         $player = $observer->Player;
[140]         if ($player != null and $player->hasPermission("sac.admin"))
[141]         {
[142]           $player->sendMessage(TextFormat::ESCAPE."$cl" . $message);
[143]         }
[144]       }
[145]     }  
[146]   }  
[147]   
[148] }
[149] 
[150] //////////////////////////////////////////////////////
[151] //                                                  //
[152] //     SAC by DarkWav.                              //
[153] //     Distributed under the AntiCheat License.     //
[154] //     Do not redistribute in modyfied form!        //
[155] //     All rights reserved.                         //
[156] //                                                  //
[157] //////////////////////////////////////////////////////
[158] 

Backtrace:

PocketMine-MP version: 1.7dev #83 [Protocol 137; API 3.0.0-ALPHA8]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux test 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64
PHP Version: 7.2.0RC3
Zend version: 3.2.0-dev
OS : Linux, linux

Loaded plugins:
DevTools 1.12.4 by PocketMine Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9
AutoUpdater 1.1 by EvolSoft for API(s) 3.0.0-ALPHA8
MineReset 3 by Falk for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
AllSigns 1.0.4 by  for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9
SimpleAuth 2.0.0-2.alpha8 by PocketMine Team, shoghicp, awzaw for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
PurePerms 1.4.1-1.alpha8 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
iProtector 3.1.0-1.alpha8 by LDX for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
Broadcaster 1.17 by EvolSoft for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
AlwaysSpawn 2.2.3-2.alpha8 by Philip Shilling for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
FantasyProtection 2 by Enrick3344 for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
AdvancedKits 5.1.0 by luca28pet for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWwtv20a2/iuzsrFNLkRaDz9VuIDXdrZG7bWu5SAXqApjRI4k1nyVM7SsFvnv9ztnhg8pTpom
DbAGuhHPzJw57xe5f3RMlKjOqH/QOzweHA+HR92OKoqs6Iz+6Jh1jqXO5cP57c346vry4fLu7vau
0+0kSmu5oLULFcSykCbKUpHNxYUsHt/Jp+l0cnbO/zMaZel5liQyDV/lWfCoTBKlajoNLGw6dYsT
lYaqELua/+2KT+0Vu0ESdsVuLGcq7gpZFHItdmWx0K9FUmojZkrgTA6qZrESq8gsN/DlcbmI0ul0
zP/+S2r1jai0P7pCmyJKFy8SPBKzLIsh0nkUkzwhMi+R2qhiTxfBnpPnHsD0H/bFuAzq2j9+3+1Y
RjojU5Sq2wmyUJHW+sMTIBLubzeP5Ro0n4rdbKZV8aQK74cxw74Huv5+r7U5motX1YF/nIq0jGPB
rFiY98NS6rEqkkhrKPzVtKNl4MsQAph2Xr9mdP0Wuj8YMmhBRIOKZHhj7ejVvXo2b7IikWY0upyc
n40v/WlnN4inHeGLXWdtry29wxa69wzZryH2+cA9vxeCnw/5uXo64if+eYyf9ghJjH4ckDT2vuiP
j/f5uPjLf+74oDkObYvZunIo/7OOD5vjFxEZ3aw0KhQlG61ZKnGWmuh8qaQR11GgUq389vH91vFM
pJkRhQprPCJKRZKF63kElHMo6x9btx80x89gN0W0WBoNFGx0of9nxB9+neiOvk5xMAWydjiVKWQA
P/r5l25noVJVyJicKpUUJTtjdvgb+KB3M8ZBeBN5Alb6/lGongCalVEcdkbHQ/hnkZksgHuP+hRX
ZR5h49Dv+T3v7Hr849kxti8iA2DvM/9woJCPcTSjM/6x3wegdLRdR2n5LIxCANz393HHydBjDqJA
7PT7h97bWZmaUkxuxuJNEYmzciH6fTHoj/pHo4O+eHt/Lga9/pF4Pj58ONwH5nyZA++RP/B7d+dD
AH6HzzILgHiWXex5yHR1PQD8EPNDHaI0ifBCPd0j1umWOGvQpiT7A5+ul6VZZgX2/9ySu7hXMun8
4qT5c1ucRzizJd3W4wkdUqlESgirkBmqHBxpq22dzc1FG5BICq41kdNpi9w4kySJyf3Z3f1bsoSV
munIEFNLY3I92tuDZpflzEcW2GvI36txQDhnpcne5qFEtG8JpQ3dksumUC6fsngCol+WxvEGv3MZ
689luEXAdHpDsM/id7Va+QokEVrfPBKDxPEdAoBpsdfA2swNN1l7I+PHz1Tyl3KJvY9R8Qi1Uv6m
MGXAbYs4x/L4dnL/7vbu+mKDaVZfHE+iRdo26Bq0qbjelj1/tfn+FUZ1WTzJ6VTGsSbSptMWkX/K
4yRK8ljBIpYtLlvANp8DpnbgyzhfyuNPOzDIXWaLZRTktG/1u1x9Y3U3NKMubdP/xZ7cwgJBjctC
UWnUtoYGtmkO+37f678opsP9N296PfFPMS6yX1VgrtJ5lEZm/Y2F82DvRUlcUdz6+Wdm8pKU6KyN
/HsNHkgpAl8GfGXtgNcCboQEH47zETldX/zfNxYJbphOG8q2A+FniwJ4vJvz8eVei0sI4l8F8ARc
6Lck0YZuhf6jvxL7/zYptAj63FTwciY4i1dyrSe5XKUb4bKBbkaSgT/8WCRZRnGUiwn+QZWx+MYC
yPk27S6jKEoUa6J4Or2GJFhTnxAJMf9GpkbqtTMAZrEWwYdrG4LY0nqKYu5xOETL823Z/oCqz7N/
1nT4JNNAhT9FZiMztsFtFg/IzTfZjMtADo5z9a2tu03TFzt4TezeBovvqfiVBZiH71R0cPvtoy3I
VWEiRZXyzrh+EucZwv1C0ChgWkzTnUmZitvAiL7oDUeD/VF/UBfptJ5kJjylVBQUcm5GYnwpJnwD
LbpWn6T/Z3vyrDCn/ZP+cEDABU6gz1OnPb5DPnu2Y9en/R6D2Pi9vDaNU69P4NUSIvJi9Iun2XxO
EKsT77dSFetTmFADKgIcsxD66edS61VWhKf/w3/TVKZpVkKW7m5PBstIPalEpUa7g6hnspU3j6nN
rG60pMk0SmAFbp+FJdmsAqB3BeKaTXd0KYswyIr6OX/K3f4wms+joIzN+pQZtV0h4riHOtEgKuhT
AsegL7byBitx2MC0UmFrC03VTi8u35y9vb5nRlBue1o+KXffU6RWHvXdZEynxwTKUhr7eJZe3kSd
Vz188tdJTKYkyIRFwFZUuqEcGRO162KjdYVxifslCl1R8SBkoXhGkKWwRLOURgSkBZ6mRWkQlyH6
fqD/wIgJ1yRLFM3/zIc4tZyrrsiwUmhCKWaFko9inZWFw0VjJ7AW8WQBV2VFAcuK14T4P2pVo9sL
1VxCD1qssvQ7I2SeK1kIkl8CZgNYxBrkg4hIW75XS5WKMl8UMgQCf5qSzVtko2kqdu6XhYLNAgQq
YpkuSrmg2WFoReb8Q0d4jjPgj35nodLR86UKHBebB0FAFSVU6q+ixyhXYST9rFjs0dPeNVT7kM0f
ria3D4fDE2/wQOcgxhrRSEwR0BbTDl30bqlIdsJkgkZmAly6gSLUVMhUx5KGPLzM0mRKQQd+KcMq
RaceBUosZRrGrOQEiK0bNFdy4ARcL0sTZuQyduxGxNiQIYI40yq0ZJ2R+wlydxptujZfPEVS/C/5
O7aw33tuZSSo46aDkyXOSbJSnYEad4tVlXSIRKlhhIjhMATm7mx8hZ1IECHJqVnwQNYMRDXoLznC
VHhoeEleLWCusAgidbYWzo6w3cWjerURw847pHwoEyYlw5DGWNbyiEzY2iPIkeisOCQJ2NtMkTwg
dPVbKWNSxyJ6wt4nGZdKvHJXIna/BnJ7H+KgotjrQZuLhSpGWKWb/1MmM0gb7nSm12lwL/UjLL54
hAP5tP5W2wlczSTtWhYZQiZMArt1V3AIEi5UwWS7PBEHF5R1WSxIagRLyhSeQ1sY94RNBvzAuYrs
GYHUKIgA7LCppzVpJFVLztWcPJS2kCd2RWS+g+RMwadCRVmCrXDrrHgFDqBnMSCJMA+e43LEmMhb
KUYXa/bVf8fZDIKlXC4sGNaXRIbnkmohZ2sDgsTEktLjyyNN6rWeDp5WERPGwhaUPSyeSv6a5TKP
YC4IU4jVKaOaI0ZUN1r1g5mSjXaRgY/siaerEVnmgon0mLCR6E05VHBUNgg1MvwvJ5/qok8QTzny
q4jXJsv5fheqanocNi3gUlQMIMo4aujOiqR+b7BvqWLHeMfW4ojT3309eaiR9JLpIS8SQYlElCIR
CfWsgpIDXWbptYZKiaverZ4D5HndsMOufHt/ORL3P15NxPXVzdU9Atn4+upygjrsTqC8/Onyriuw
SdzfYtelePfj7fWlGN/dnl9OJv6WX3xEFmiuo4xTM8UlTdwFnJycKOrY04fYEXZD8jfe4SE2KBt1
OKVlKXhEtIINEa8fMzFrWqj3Ys52FPfstikXH4QDkaiJajY00w23FE4p2/N2/8PNZAKulIe+chVQ
UWBlSrRahdqzNQOwKpXrhs1hz/GpX79IkON6aLleyGIGX/CCLI5tPUvR5kWpsmsRKe6McGcQxxKZ
llx+tKlAaVbC8F53q/i4ZXnO9GyOmc+rOJk0HueLW5v7rYkjN2dlHNaERIimq1Q0pJMPi5wpB4OH
vZ7lUey84ajwQZ5gW7Gna6bmRZZU6YbOunWvbYktnYIJp7ptU3jBftq2MKmKRNJQkXF/XZlsWCa5
LVds2ebgHsGtei5oh9vNFDN5Fd14Qn6jl5f6Q5EiXyGXAf0T7EnrUmn7ilirRVVeUliiuxqSupXe
bHZ0VSSRxhs/Ih0OYs9esCzTR20Jv5FIqmWCgoLfylV1PmlNuDevfH0jSvIJJz8Oi4LReVTTlkiV
+04NF5ld2LZOfjOfVhhoa+UHFo/b9jeolGsOL0CvpiyzTmTVRbRQF2qfRDVNU2VImHWVDsuPbdEz
kwbNINWckhoa1DrQrYvwHF9sD+JWbWB3HwRQ+cMi3GmngmqF4lqxNoS7K7x+y1dJzXytZypSEDUP
Dm3QbMoq7u+opgmtDqle55KTzgLoaPLFj2ha+Z18QrXp+fhtF2dBwQwmv4pCGCMnaA5fNXqP0Y/E
kasBm+pQs2BaW31xFiJcLGU830M/ZwvWUMG83EW4UtCggzTcco464bRwtUriy2eKLVTxyrhr4xZd
/C5K0TCALZiN4phCZd3bcTquisKmPaN6lw6tkMqm1Juluece2+U3um41KxdW/ZlLCYIKg4IN2iVk
qmspttJ7Sb9e1WQRXK7my9yP0ojI6DNv1Q7ri+9kkVI6ap2kjtUlIMLiEMD7kRaJmWZnIuGZCVRq
SIhFmdKHNOTG9G6cXRqYq1xG14HH1IvmnoM1LQsC0g+iT4Wzq5KoQ2L+q+6IOaJA5rqmqbO1EbPl
eh4t9hBLTAmP2FsE1nbo+xPdaHCa2hAzsh1shs6JLLXqL1XVO3EYCqWR6N6fXJyjCUU1jqGlmn4J
zuHiShorVbBjh3BVwcqNAMyJywado0riMiLNAhrk8kkYzw3kGUiynCR7qtqqVnSmCcMMve0jxeco
WLKqaD6xhgHYaUTMGon5sBO6nRJVGC2ZLYG0qSX9aXuFnVFoKxPq8pxMdH0pIyLJtOj+28hFv2wk
k9ByiGqWtDG+UFUvy19kSGMHN7zVhb5Su946AD7D0c8d8eyRkchhJU9RzHX1hrMGSMFIJA4dBxEu
uCAWChqGAseg5wokSmC27iKboJkWwV2xVZnKBrgqZW3XO6FoTTY+k1q1LnvVR5x84ZauGGCh/9KC
MoH/mmO2Vm0q2FnuCTMNUSqVKuQlex9ZqBUWj6uaORblAZ53UPLnspxfA1jcDk9LVTbfuehfxTAn
TNf5pCT7eLsK6Fa7NmaAL07duPU+SzLEHW6pucSgjMOJreKNpEJE0swBfks/uWIQO3dcPrSOsuWk
yo6SZsqimqk5ZSieoVImI/1Y3BQReLLaqkOgRCqqJFEb0bRM0fQlX7vJoKtP6hqek8ecXy5VqdKl
tnkZ28+NNLovj6JaFNjygouzgsZxhomvGP01o0GILaC1TBR7M8VAKjqqAmxbQySOSkOoy4TcFifE
HXDN0BjJpiR7L4pSFsAT8jSLIykE6o46Y7QSG1IYp/G1V/LXFq24FMRK2kt4ot7KFRd8kYssFE9I
2zbpwF+QiBPh2BJ2pFMVYXykzbLY8eBCO2KBrlc3QmlmRpVc/A8F49LRSkbcFf9WKpsfYTfuPEca
hnsahjASx1+ELc/yMnbY3G8qhbYQT1MOAl5uU5t9AeCxfZJlUhsEY0rJ0mpo38UjymsjYXulylwg
/bTMR+LENlDW0Dla2crB4QKWox6HbfvGAUgPbKani2ogw2Qyi+BRdosb+tvx38hGP5pU8vzBQm1N
5wzQesZ24UA+49HseBNSp4gNKCqZKJ1njYkhMXh2UF3tW2ZkaUyEnycJKh+ewck0S9cJNdDsiBqi
1jXNNBFwy6JZZtq5fpCLRaEWbgRZD3epPaHv7B5fZswSQui033rLgZ6gFp31GNb29mmYh10d1VWX
K5ua5oOhWYv3nXN6M8GjchVnOaXkruDXz12AwQi9DjBVM4BiZq4KtGMexeuUCjHa5Iq5kvQF72/h
Eu59Z6vIK9HyaGMDfhVaHTbSmV2u8G8ryTLY1hLiXV0XuMqOMNL2qiInpVBiodu4PHZnquG2X6N3
C238lQg/WTm65Maac3bcGppVI38TGSvGajy2dDCOXNQAu57NhS6avqOpDblzieY1HnSu4KKpyVrF
NqNzQbpqKpGQUA9YCV0+S6q87APV26DPqWhU6YqXEBxoaDkSP3P9iyqgy1PMXwijzUhVKdZ+8cUc
0GS1oHdHPDOq3hpyw/JSRueimMsMzb0ZDx+glwiEuhqsRTrfygTwL0EvGSnUcRpubhuJN9dn96PB
90fdg5Pnfnf4POwOvu9/H6JUslH+lSkUHhCRT497NhnYp/2D1/yeUT0bFMHU89Dr/HPUA5sfhZIl
bkLAUap1vAnMg+2D+rc4Mmq49Ymp/bi1BZkFqEiXmzB6w5WGstiCuv/DQhtUFlt0zKOYP7rZgJmt
D10XyRZgiaBoP+XDw6/afZVzyI/JzL6P2zwxGV9vCyA1W7RQfQcuwq2Ndch74ASJRpe+mu303JcS
eaaj560jbkLoPptynyLfqXlcfXCyce0yybb403yn3gQma6iIv/h1v8SBDyIG9Omv8Og7hIPefu8I
P3evYHyz4cnhycG+UrNB2A9PVHh00hvMjmdSDYZHs8Hx0XzQl4CLXeAeL1l79M0gfeRiskeVIp1v
KeYdeiDEWmZ+6BNkLfldd3Xu9yi330cd8NexTGfUxvH+/f8DBsoIeQ==
===END CRASH DUMP===

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
