### ISSUE TITLE
kicked for flying

### ISSUE THREAD

**Issue by Matthww** [DarkWav/SAC#67]
Whenever you "combo" someone and they stay up in the air because of the knockback they will get detected by the fly detection.

**Comment by DarkWav** [comment]
Tanks for Bug Reporting! I will fix this ASAP. Sorry for the inconvenience!

**Comment by DarkWav** [comment]
fixed with commit 609e06dbb4775072e485bf11ad9614a1493eddb6 / Version 3.3.5.
Please make sure to update to version 3.3.5.
If this bug still happens then, comment on the issue or open a new one.

**Comment by Matthww** [comment]
This is happening again.

**Comment by DarkWav** [comment]
Thanks for Bug Reporting!
I will take a look at this ASAP.

**Comment by DarkWav** [comment]
Reproduced.
Seems like I updated the API the wrong way xD!
I will fix this ASAP ;)

**Comment by DarkWav** [comment]
Hopefully fixed with commit 503221e5c92bf36c6c3c4879ca95b96da1de70ff / Version 3.4.4
Please make sure to update to this version!
If the issue is not fixed, please reply to this issue or open a new one.
