### ISSUE TITLE
Climb water

### ISSUE THREAD

**Issue by Matthww** [DarkWav/SAC#68]
If you climb up water you get kicked for flying

**Comment by DarkWav** [comment]
Thanks for bug reporting!
What do you mean with "Climb up water?" You mean e.g swimming up waterfalls?
I will do some testing with this.
_**EDIT: I tested this bug and its critical. I will now fix it ASAP. Thanks for bug reporting!**_

**Comment by DarkWav** [comment]
oops xD

**Comment by DarkWav** [comment]
Fixed with commit 9c762800153ce2fe8487c79b47565efe3779c9cc / Version 3.3.6.
Please make sure to update to this Version!
Thanks for reporting bugs, it really helps me a lot ;)
Please comment on this issue or open a new one if the bug is still present in Version 3.3.6
