### ISSUE TITLE
noclip bugging

### ISSUE THREAD

**Issue by Matthww** [DarkWav/SAC#69]
If you would go from a slab to a full block you it will be detected as noclipping same for going up stairs

**Comment by DarkWav** [comment]
Thanks for bug reporting! I have been aware of this problem for some time and i'll try to fix it ASAP.

**Comment by DarkWav** [comment]
Fixed with commit 2bd8602cb34d5bfc5d932b87838f2e743f3a4be9 / Version 3.3.7.
Please make sure to update to this version!
If the bug still happens, please comment on this issue or open a new one.
Btw you're a really good bug reporter, i enjoy it ;)

**Comment by Matthww** [comment]
https://streamable.com/8e6yr 
still happening

**Comment by DarkWav** [comment]
OK, i will have a look at this again.

**Comment by DarkWav** [comment]
I rebuilt the situation and can confirm that this bug happens.
I will fix it ASAP, thanks for reporting.

**Comment by DarkWav** [comment]
Hopefully fixed with version 3.3.8. 
Please make sure to update to this version!
If it still happens, please comment on this issue or open a new one.
