### ISSUE TITLE
Fly detection

### ISSUE THREAD

**Issue by Infernus102** [DarkWav/SAC#7]
Player are getting detected for fly when they are climbing a ladder

**Comment by DarkWav** [comment]
let me see....
are you useing the default config?
which server software do you use?

**Comment by DarkWav** [comment]
does this also happen on VAC 3.0.0???

**Comment by Infernus102** [comment]
Idk player complained, maybe they were lying, and its genisys and yes default

**Comment by DarkWav** [comment]
are you 100% sure u use vac 3.0.1 and NOT 3.0.0?

**Comment by DarkWav** [comment]
i know that there IS a FALSE POSITIVE with ladders in 3.0.0, but this was FIXED in 3.0.1.

**Comment by Infernus102** [comment]
Yes bro and i said they could be lying, btw also one time it detected when a player was going through a door and this plugin kicked him for noclip

**Comment by DarkWav** [comment]
eeehm then u don´t use the default config! the DEFAULT Config DOES NOT kick players for noclip!
NoCLip is still a bit buggy and thats WHY i set it to not kick!

**Comment by DarkWav** [comment]
"#I do NOT reccomand to kick players for NoClip due to glitches!" - i am sure you didnt read this comment in the config. set "NoClip-Punishment" to "block" to prevent false positives!
however, i try to make that better in vac 3.0.2.

**Comment by Infernus102** [comment]
False reach detection too and thats default settings

**Comment by Infernus102** [comment]
Just got complains

**Comment by Infernus102** [comment]
See ![screenshot_20161008-215752 01](https://cloud.githubusercontent.com/assets/22660649/19214477/ea41755a-8da2-11e6-96b5-585b8813b9df.png)

**Comment by DarkWav** [comment]
you CANT get kicked for NoClip when useing the default conig. thats a FACT!
UPDATE your config as well... im doing my best... and one other thing:
set every chec`k`s punishment that is causing false positives to "block". that PREVENTS false KICKS
if you want to allow someone flying then give him the permission "vac.fly". that should trigger all fly
checks so your players can fly. it momentary also triggeres noclip but ill fix that.
for now:
set "Reach-Punishment" to "Block" in Config. (That fixes all false positives with reach!)
set "NoClip-Punishment" to "Block" in Config. (That fixes all false positives with noclip!)
give all you players that should be able to fly the permission "vac.fly".
DISABLE FLY AND GLIDE AND CONFIG ON EMERGANCY.
im working hard on 3.0.2.....

**Comment by Infernus102** [comment]
False kick for speed when they get hit by knockback...

**Comment by DarkWav** [comment]
speed... i guess i have to add the sharpness config option.
they are getting kicked ... because of a 

### kockback enchant

(probably)
I have my problems but i do not support enchnats yet because i am focusing on compatiblity for

### PocketMine-MP

not for Genisys...
Enchantig is not implemented into pocketmine.
I will ad a option that will allow you to increrase the ringbuffer (the amount of moves which averange is taken for the detection.) that should fix it.

**Comment by Infernus102** [comment]
Bro everyone uses genisys now..

**Comment by inferboy** [comment]
![Uploading Screenshot_20161009-105126~01.png…]()

**Comment by Infernus102** [comment]
![screenshot_20161009-105126 01](https://cloud.githubusercontent.com/assets/22660649/19218143/30bfd492-8e0f-11e6-85bb-b820d2e22531.png)

**Comment by DarkWav** [comment]
Use My

# API (Permissions)

YOU HAVE TO GIVE PLAYERS THE PERMISSION "vac.regen" when they execute the /heal commmand!
(MODYFY YOUR /HEAL /FLY /BACK /XXX PLugin!)
iF YOUR HAVING MASSIVE PROBLEMS WITH THIS PLUGIN UNINSTALL IT UNTIL I RELEASED 3.0.2

**Comment by Infernus102** [comment]
what permission for /back?

**Comment by DarkWav** [comment]
Sorry, but i cannot provide compatibity with thousands of plugins, theese plugins have to
make themselfs compatible with mine. i CAN try to do that for /fly, but /heal is NOT possible
(the author of the /heal plugin has to provide the comaptiblity.)
If you give me your plugin i can rewrite it so it will be comatible with VAC. i cant do nothing more.

# Ant to that everyone uses genisys: i use This: https://github.com/pmmp/PocketMine-MP

**Comment by Infernus102** [comment]
so heal wont be compatible for vac.regen?

**Comment by DarkWav** [comment]
if you give vac.regen to players before healing them, yes.

**Comment by Infernus102** [comment]
ok ty

**Comment by Infernus102** [comment]
do u know how to fix /tpa of essentialspe?

**Comment by DarkWav** [comment]
if the player is teleported, give him "vac.fly" to pervent movement kicks/blocks (you have to editt essentialspe)

**Comment by Infernus102** [comment]
no i mean that infamous /tpa glitch of essentialspe where when a player uses /tpa it works same as /tpahere

**Comment by DarkWav** [comment]
I have no idea how to fix that... sorry.
and: i found a solution for the speed false positives on knockback.
and for Reach as well...
i still have to test a bit for the ladder glitch.

**Comment by Infernus102** [comment]
ok yea fix ladder glitch because its a prison server and there are ladders for mines

**Comment by DarkWav** [comment]
ok but it will sadly not get realeased before afternoon (world time).

**Comment by Infernus102** [comment]
its ok till tomorrow 👍

**Comment by DarkWav** [comment]
fixed with commit 64effed556b0b96fd1497c191aee9a32ff4d8681

**Comment by Infernus102** [comment]
did u fix fly detection when on ladder and speed detection by knockback?

**Comment by Infernus102** [comment]
???

**Comment by DarkWav** [comment]
yes i fixed them.

**Comment by DegenApeDev** [comment]
It seems that sprinting is causing speed detection kick any fix for this?
