### ISSUE TITLE
speeding on ice

### ISSUE THREAD

**Issue by Matthww** [DarkWav/SAC#70]
If you sprint jump on ice you will get kicked for speeding

https://streamable.com/tk2y9

**Comment by DarkWav** [comment]
Thanks for Bug Reprting!
I will fix this ASAP.
Seems like i haven't thought of ice yet xD.
Sorry for the inconvenience!

**Comment by DarkWav** [comment]
Fixed with Version 3.3.9.
Please make sure to update to this Version!
If this bug still happens, please comment on this issue or open a new one.
