### ISSUE TITLE
Custom Enchants

### ISSUE THREAD

**Issue by Matthww** [DarkWav/SAC#72]
Add support for Custom enchants, some of them give you speed or extra jump.

**Comment by DarkWav** [comment]
Thanks for the Feature Request!
SAC currently only has support for enchans that are in pocketmine by default.
If you have a plugin which adds custom enchants that trigger SAC, there are 3 Options:
1. Ask the developer of the enchants plugin to add support for SAC. (with bypass permissions)
Send him/her the link to SAC's [Developer API](https://github.com/DarkWav/SAC/wiki/Developer-API)
2. Change the plugin yourself so it gives everyone who has custom enchants the bypass permissions for SAC (e.g. **_sac.fly_** for fly exclusion, **_sac.speed_** for speed exclusion, **_sac.regen_**, or just **_sac_** for bypassing all checks)
3. (only if you enchants plugin is public) show me the source code or link to github site of the custom enchants plugin and ill check if I can add support.

You can take a look at the [Developer API](https://github.com/DarkWav/SAC/wiki/Developer-API) if you want :)

**Comment by DarkWav** [comment]
I looked at this in detail and and i think at this time it isnt possible to add support for custom enchants without modifying the enchants plugin itself. Im very sorry, there's nothing I can do on SAC's side, but
the points I stated above should work.

**Comment by DarkWav** [comment]
Im sorry, but since I can't solve this issue, i will close it now.
However, if you have any further questions, you are still free to ask them :) .
