### ISSUE TITLE
SUGGESTION - Broadcast for staff

### ISSUE THREAD

**Issue by YHC2538** [DarkWav/SAC#73]
In config.yml line 65

Instead of sending the hacker warning message to all ops only, can you make it so that it also sends it to  non op staff too?

The idea is for my server's trainees and mods. For ex. If they have the permission _sac.hacker.warning,_ they can also get the hacker alert without having op?

**Comment by DarkWav** [comment]
Thanks for the Feature Request!
This feature technically already exist. there is a permission called "sac.admin".
While it is deafaultly given to OPs, you can technically give it to anyone you want, including your trainees and mods for example.
All players which have the permission "sac.admin" should get notified about hackers.
If you have any further questions, feel free to ask them :)

**Comment by DarkWav** [comment]
Since the question has been answered, i will close this issue now.
If you still have any further questions, feel free to reply.
