### ISSUE TITLE
Boostblocks

### ISSUE THREAD

**Issue by YHC2538** [DarkWav/SAC#75]
AntiCheat for speed kicks players when they step on the boost blocks, how to fix that?

Using this plugin for boost blocks:
https://github.com/legoboy0215/PocketMine-Plugins/tree/master/RocketPads/resources

**Comment by DarkWav** [comment]
Thanks for bug reporting!
Sac is not compatible with 3rd-party movement Plugins at the moment. However, you can modify the BoostBlocks Plugin to Support SAC via the DeveloperAPI , or disable the Antispeed completely in the config
If you have any further questions, feel free to ask them :).

**Comment by DarkWav** [comment]
I looked at this a bit more in-depth and maybe i can add some function in SAC to fix this aswell, so eventually you don't need to do the steps which I described above.

**Comment by YHC2538** [comment]
Thanks!

**Comment by DarkWav** [comment]
**Development is paused until PocketMine-MP fully supports MCPE 1.5 as i cannot test without it, sorry.**

**Comment by DarkWav** [comment]
Ok we can continue :)

**Comment by DarkWav** [comment]
Fixed / Added with Version 3.4.7.
Please make sure to update to this version!
If this feature still doesn't work, comment on this issue or open a new one.
If you have any further questions, feel free to ask them :)

**Comment by YHC2538** [comment]
Thank you again! :)
