### ISSUE TITLE
Glide issue, false kick

### ISSUE THREAD

**Issue by YHC2538** [DarkWav/SAC#76]
When you fall from from and high place and land in the cobwebs, it kicks you for gliding.

**Comment by DarkWav** [comment]
Thanks for bug reporting!
I will take a look at this ASAP :)

**Comment by DarkWav** [comment]
Reproduced. It appears to be an extremely critical bug in the AntiGlide check.
I will fix this ASAP. Thanks for contributing!

**Comment by YHC2538** [comment]
Thank you :)

**Comment by DarkWav** [comment]
Fixed with Version 3.4.7.
Please make sure to update to this version!
If this bug still happens, comment on this issue or open a new one.
If you have any further questions, feel free to ask them :)

**Comment by YHC2538** [comment]
Thank you! I will test it right away when In able to :)
