### ISSUE TITLE
Fast Click Bug (KillAura)

### ISSUE THREAD

**Issue by YHC2538** [DarkWav/SAC#79]
Can you up the limit to 15 CPS for the Fast Click in the "KillAura" section? Some of my players can jitter click really fast up to 12-15 CPS, which kicks them every time when they are in a great combo.

**Comment by DarkWav** [comment]
Thanks for your idea & bug reporting. I will add a config option where you can define the max cps and set it to default 15.

**Comment by DarkWav** [comment]
Hopefully fixed with version 3.5.0.
Make sure to update to this version!
If not, please reply on this issue or open a new one.
If you have any further questions, feel free to ask them.

**Comment by DarkWav** [comment]
I think this error hasn't been solved...

**Comment by DarkWav** [comment]
Hopefully (now) fixed with version 3.5.1.
Make sure to update to this version!
If not, please reply on this issue or open a new one.
If you have any further questions, feel free to ask them.
