### ISSUE TITLE
killaura broken

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DarkWav/SAC#80]
Im on windows 10 and wen i attack someone after 2-3 hits im suspected of killaura... Will anti fast clicks work without killaura ?

**Comment by DarkWav** [comment]
Thanks for bug reporting!
1. Try disabling heuristics (set heuristics and deepheuristics to 0), angle and antireach.
If the bug still happens, please report it her. If the bug no laonger happens, Its probably a problem in
AntiReach/Heuristics.

**Comment by DarkWav** [comment]
Btw is Type "Angle" or "Generic" or both??

**Comment by TDMidkwhatisxd** [comment]
generic

**Comment by TDMidkwhatisxd** [comment]
I dont wanna use killaura anymore, anti-reach dont work if killaura is off ? What about cps limit?

**Comment by DarkWav** [comment]
1. AntiReach works with killaura disabled.
2. to only use AntiFastClick, set "Heuristics" and "Deepheuristics" to 0 and set "Angle" to false. This will ensure only AntiFastClick is enabled.
3. Only Generic alerts indicates a problem with Heuristics. Did AntiKillAura work for you before 3.5.0?
4. As far as i know, AntiFastClick is completely broken in 3.5.0, i would recommend upgarding to 3.5.1 to use it..

**Comment by DarkWav** [comment]
As far as i know, AntiFastClick is completely broken in 3.5.0, wait for 3.5.1 to use it!

**Comment by DarkWav** [comment]
Ok i think i spotted the issue. Heursitics still have problems, but everything else (including angle) should work fine in v3.5.1.
just upgrade to 3.5.1 and set "DeepHeuristics" + "Heuristics" to 0 in config. That should fix it.
I will work further soon to make heuristics compatible with MCwin10
And as always huge thanks for bug reporting. Without the community SAC would never get fixes for bugs :)

**Comment by TDMidkwhatisxd** [comment]
SAC is best Admin ever :)

**Comment by DarkWav** [comment]
Hopefully fixed with Version 3.5.4. If not, please reply to this issue or open a new one.
