### ISSUE TITLE
Add Feature

### ISSUE THREAD

**Issue by Reflyansyah** [DarkWav/SAC#81]
• Anti AimBot
• Anti Critical
• Anti Jesus

The choice is yours

**Comment by DarkWav** [comment]
Thanks for your Feature Request!
Aimbot should be detected by killaura heuristics, you might need to makes them more agressive dependending in the aimbot. (But only in 3.5.1+)
Anti Jesus is really important, thats what im planning to add.
Practically every Anti criticals can be triggered by a Client without Hacks so i won't add that ;)

**Comment by Reflyansyah** [comment]
Thanks You

**Comment by DarkWav** [comment]
No problem ;)
