### ISSUE TITLE
Fly false detect for player with different scale

### ISSUE THREAD

**Issue by boi1216** [DarkWav/SAC#82]
When I set player scale with
`$player->setScale(5);`
it detects fly

**Comment by DarkWav** [comment]
Thanks for bug reporting!
This seems to be a conflict with plugins which change the Player's scale to a non-vanilla-like size in
combination with a wrong implementation of the "isOnGround()" function in PocketMine-MP.
I will see if i can fix this, would be simmilar like motions support i guess.
Nevertheless, i've got a different problem. I will go on a trip for 7 days on saturday, and i will be unable to
maintain the project during that time. (I got a desktop PC which i can't take with me).
I will give my best to fix this today + tomorrow, but if i cant't, you'll have to wait for 7 days, sorry.
However, I'm confident it won't be too hard to fix.

**Comment by DarkWav** [comment]
Ok this should be fixed with version 3.5.2.
If not, reply ln this issue or open a new one.
If you have any further questions, feel free to ask them.
