### ISSUE TITLE
error pls fix

### ISSUE THREAD

**Issue by FSociety-Elliot** [DarkWav/SAC#85]
[11:48:09] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\enti
ty\EntityTeleportEvent' to 'SAC v3.5.3': Call to a member function getName() on 
null on DarkWav\SAC\EventListener
[11:48:09] [Server thread/CRITICAL]: Error: "Call to a member function getName()
 on null" (EXCEPTION) in "SAC-master/src/DarkWav/SAC/Observer" at line 1581

**Comment by DarkWav** [comment]
Thanks for Bug reporting!
I will take a look a this ASAP.

**Comment by DarkWav** [comment]
Hopefully fixed with Version 3.5.4. If not, please reply to this issue or open a new one.
Sorry for the extreme time delay, i had been busy at school.
