### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by ghost** [DarkWav/SAC#92]
What was the latest anti-cheat version for PHP 7.0?

**Comment by DarkWav** [comment]
Theoretically, you can try to use a new version which is made for PHP 7.2 on a PHP 7.0 server.
If it does not work, you can try the 3.4.X series.
Technically, SAC works on any PHP version which works with the latest pocketmine-release.
Note that old versions of SAC do not get any support and are very likely to contain major bugs.
If you are searching for a version that still supports API 3.0.0-ALPHA7 (Last version of PMMP to still support PHP 7.0), try [3.3.9](https://darkwav.github.io/ac/SAC_v3.3.9.phar)

**Comment by ghost** [comment]
thank you very much

**Comment by DarkWav** [comment]
No problem ;)
