### ISSUE TITLE
Found Stolen Plugin

### ISSUE THREAD

**Issue by Aericio** [DarkWav/SAC#93]
I recently stumbled upon an anticheat that seemed very similar to this one (because it is):

https://github.com/PlexOfDevs/PAC

Violations:
- Source is not disclosed
- Changed the owner’s name
- Made himself the copyright owner
- possibly others.

Just thought I’d let you know.

**Comment by DarkWav** [comment]
Thanks for notifying.
I notified the author, however, fortuanately, its not a too dramatic violation.
1. GNU Genereal Licenses are not that bad.
2. Source code was released.
3. It appears to be a really old version of SAC, (3.3.10), which is full of bugs, so I don't care xD
If someone is dumb enough to pay for a free Plugin, its not my fault.

**Comment by Aericio** [comment]
Alright, lol.
