### ISSUE TITLE
Necessary rewrite information

### ISSUE THREAD

**Issue by radondev** [DarkWav/SAC#96]
Since I've decided to help you rewrite this repository, I need some additional information. Therefore I would like to contact you by email or discord (which suits you best).

I see a number of ways to optimize the existing code to become more readable and performant:

- more OOP
- (configuration data) caching
- replace old functions with faster ones (UUIDs instead of spl_object_hash, ....)
- PSR coding style
- general code reduction

Kind regards, Noah

**Comment by DarkWav** [comment]
I basically gave up on SAC as I cannot handle the development efforts to update it any more.
The Regular "SAC" is a complete mess from a code base point of view, If you make any changes I'd highly recommend the architecture from "SAC-rewrite" instead.
However, many checks still have to be ported to the new Architecture and it isn't stable yet.
You're always free to fork my software if you want to.
